// src/players.js
const players = [
    { name: 'Manuel Neuer', nation: 'Germany', age: 38, position: 'Goalie', difficulty: 1 },
    { name: 'Thomas Müller', nation: 'Germany', age: 34, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Ádám Szalai', nation: 'Hungary', age: 35, position: 'Striker', difficulty: 2 },
    { name: 'Dominik Szoboszlai', nation: 'Hungary', age: 23, position: 'Attacking Midfield', difficulty: 2 },
    { name: 'Andrew Robertson', nation: 'Scotland', age: 30, position: 'Left Back', difficulty: 1 },
    { name: 'John McGinn', nation: 'Scotland', age: 29, position: 'Midfielder', difficulty: 2 },
    { name: 'Granit Xhaka', nation: 'Switzerland', age: 31, position: 'Midfielder', difficulty: 1 },
    { name: 'Xherdan Shaqiri', nation: 'Switzerland', age: 32, position: 'Right Wing', difficulty: 1 },
    { name: 'Sergio Ramos', nation: 'Spain', age: 38, position: 'Center Back', difficulty: 1 },
    { name: 'Alvaro Morata', nation: 'Spain', age: 31, position: 'Striker', difficulty: 1 },
    { name: 'Luka Modric', nation: 'Croatia', age: 38, position: 'Midfielder', difficulty: 1 },
    { name: 'Ivan Perisic', nation: 'Croatia', age: 35, position: 'Left Wing', difficulty: 1 },
    { name: 'Ciro Immobile', nation: 'Italy', age: 34, position: 'Striker', difficulty: 1 },
    { name: 'Leonardo Bonucci', nation: 'Italy', age: 37, position: 'Center Back', difficulty: 1 },
    { name: 'Elseid Hysaj', nation: 'Albania', age: 30, position: 'Right Back', difficulty: 3 },
    { name: 'Thomas Strakosha', nation: 'Albania', age: 29, position: 'Goalie', difficulty: 3 },
    { name: 'Harry Kane', nation: 'England', age: 30, position: 'Striker', difficulty: 1 },
    { name: 'Raheem Sterling', nation: 'England', age: 29, position: 'Right Wing', difficulty: 1 },
    { name: 'Christian Eriksen', nation: 'Denmark', age: 32, position: 'Midfielder', difficulty: 1 },
    { name: 'Kasper Schmeichel', nation: 'Denmark', age: 37, position: 'Goalie', difficulty: 1 },
    { name: 'Josip Ilicic', nation: 'Slovenia', age: 36, position: 'Right Wing', difficulty: 2 },
    { name: 'Jan Oblak', nation: 'Slovenia', age: 31, position: 'Goalie', difficulty: 1 },
    { name: 'Aleksandar Mitrovic', nation: 'Serbia', age: 29, position: 'Striker', difficulty: 2 },
    { name: 'Sergej Milinkovic-Savic', nation: 'Serbia', age: 29, position: 'Midfielder', difficulty: 2 },
    { name: 'Kylian Mbappe', nation: 'France', age: 25, position: 'Right Wing', difficulty: 1 },
    { name: 'Antoine Griezmann', nation: 'France', age: 33, position: 'Striker', difficulty: 1 },
    { name: 'Virgil van Dijk', nation: 'Netherlands', age: 32, position: 'Center Back', difficulty: 1 },
    { name: 'Memphis Depay', nation: 'Netherlands', age: 30, position: 'Left Wing', difficulty: 1 },
    { name: 'David Alaba', nation: 'Austria', age: 31, position: 'Center Back', difficulty: 1 },
    { name: 'Marko Arnautovic', nation: 'Austria', age: 35, position: 'Striker', difficulty: 2 },
    { name: 'Robert Lewandowski', nation: 'Poland', age: 35, position: 'Striker', difficulty: 1 },
    { name: 'Wojciech Szczesny', nation: 'Poland', age: 34, position: 'Goalie', difficulty: 1 },
    { name: 'Kevin De Bruyne', nation: 'Belgium', age: 32, position: 'Midfielder', difficulty: 1 },
    { name: 'Romelu Lukaku', nation: 'Belgium', age: 31, position: 'Striker', difficulty: 1 },
    { name: 'Vlad Chiriches', nation: 'Romania', age: 34, position: 'Center Back', difficulty: 3 },
    { name: 'Ciprian Tatarusanu', nation: 'Romania', age: 38, position: 'Goalie', difficulty: 3 },
    { name: 'Marek Hamsik', nation: 'Slovakia', age: 36, position: 'Midfielder', difficulty: 2 },
    { name: 'Martin Dubravka', nation: 'Slovakia', age: 35, position: 'Goalie', difficulty: 2 },
    { name: 'Andriy Yarmolenko', nation: 'Ukraine', age: 34, position: 'Right Wing', difficulty: 2 },
    { name: 'Oleksandr Zinchenko', nation: 'Ukraine', age: 27, position: 'Left Back', difficulty: 2 },
    { name: 'Cristiano Ronaldo', nation: 'Portugal', age: 39, position: 'Striker', difficulty: 1 },
    { name: 'Bruno Fernandes', nation: 'Portugal', age: 29, position: 'Midfielder', difficulty: 1 },
    { name: 'Hakan Calhanoglu', nation: 'Türkiye', age: 30, position: 'Midfielder', difficulty: 2 },
    { name: 'Caglar Soyuncu', nation: 'Türkiye', age: 28, position: 'Center Back', difficulty: 2 },
    { name: 'Patrik Schick', nation: 'Czechia', age: 28, position: 'Striker', difficulty: 2 },
    { name: 'Tomas Soucek', nation: 'Czechia', age: 29, position: 'Midfielder', difficulty: 2 },
    { name: 'Giorgi Mamardashvili', nation: 'Georgia', age: 23, position: 'Goalie', difficulty: 3 },
    { name: 'Khvicha Kvaratskhelia', nation: 'Georgia', age: 23, position: 'Left Wing', difficulty: 3 },

    // Albanian players
    { name: 'Etrit Berisha', nation: 'Albania', age: 34, position: 'Goalie', difficulty: 3 },
    { name: 'Elhan Kastrati', nation: 'Albania', age: 26, position: 'Goalie', difficulty: 3 },
    { name: 'Thomas Strakosha', nation: 'Albania', age: 29, position: 'Goalie', difficulty: 3 },
    { name: 'Arlind Ajeti', nation: 'Albania', age: 30, position: 'Center Back', difficulty: 3 },
    { name: 'Naser Aliji', nation: 'Albania', age: 29, position: 'Left Back', difficulty: 3 },
    { name: 'Iván Balliu', nation: 'Albania', age: 32, position: 'Right Back', difficulty: 3 },
    { name: 'Berat Djimsiti', nation: 'Albania', age: 30, position: 'Center Back', difficulty: 3 },
    { name: 'Elseid Hysaj', nation: 'Albania', age: 30, position: 'Right Back', difficulty: 3 },
    { name: 'Ardian Ismajli', nation: 'Albania', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Marash Kumbulla', nation: 'Albania', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Enea Mihaj', nation: 'Albania', age: 24, position: 'Center Back', difficulty: 3 },
    { name: 'Mario Mitaj', nation: 'Albania', age: 20, position: 'Left Back', difficulty: 3 },
    { name: 'Amir Abrashi', nation: 'Albania', age: 33, position: 'Midfielder', difficulty: 3 },
    { name: 'Kristjan Asllani', nation: 'Albania', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Nedim Bajrami', nation: 'Albania', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Klaus Gjasula', nation: 'Albania', age: 33, position: 'Midfielder', difficulty: 3 },
    { name: 'Qazim Laçi', nation: 'Albania', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Ylber Ramadani', nation: 'Albania', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Taulant Seferi', nation: 'Albania', age: 27, position: 'Forward', difficulty: 3 },
    { name: 'Jasir Asani', nation: 'Albania', age: 28, position: 'Right Wing', difficulty: 3 },
    { name: 'Medon Berisha', nation: 'Albania', age: 23, position: 'Striker', difficulty: 3 },
    { name: 'Armando Broja', nation: 'Albania', age: 22, position: 'Striker', difficulty: 3 },
    { name: 'Mirlind Daku', nation: 'Albania', age: 25, position: 'Striker', difficulty: 3 },
    { name: 'Arbër Hoxha', nation: 'Albania', age: 24, position: 'Left Wing', difficulty: 3 },
    { name: 'Rey Manaj', nation: 'Albania', age: 26, position: 'Striker', difficulty: 3 },
    { name: 'Ernest Muçi', nation: 'Albania', age: 22, position: 'Forward', difficulty: 3 },

    // Adding Austrian players
    { name: 'Niklas Hedl', nation: 'Austria', age: 22, position: 'Goalie', difficulty: 3 },
    { name: 'Heinz Lindner', nation: 'Austria', age: 33, position: 'Goalie', difficulty: 3 },
    { name: 'Patrick Pentz', nation: 'Austria', age: 27, position: 'Goalie', difficulty: 3 },
    { name: 'Flavius Daniliuc', nation: 'Austria', age: 21, position: 'Center Back', difficulty: 3 },
    { name: 'Kevin Danso', nation: 'Austria', age: 25, position: 'Center Back', difficulty: 3 },
    { name: 'Philipp Lienhart', nation: 'Austria', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Phillipp Mwene', nation: 'Austria', age: 29, position: 'Right Back', difficulty: 3 },
    { name: 'Stefan Posch', nation: 'Austria', age: 26, position: 'Center Back', difficulty: 3 },
    { name: 'Leopold Querfeld', nation: 'Austria', age: 19, position: 'Center Back', difficulty: 3 },
    { name: 'Gernot Trauner', nation: 'Austria', age: 31, position: 'Center Back', difficulty: 3 },
    { name: 'Patrick Wimmer', nation: 'Austria', age: 22, position: 'Right Wing', difficulty: 3 },
    { name: 'Maximilian Wöber', nation: 'Austria', age: 25, position: 'Left Back', difficulty: 3 },
    { name: 'Christoph Baumgartner', nation: 'Austria', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Florian Grillitsch', nation: 'Austria', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Marco Grüll', nation: 'Austria', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Florian Kainz', nation: 'Austria', age: 31, position: 'Midfielder', difficulty: 3 },
    { name: 'Konrad Laimer', nation: 'Austria', age: 26, position: 'Midfielder', difficulty: 3 },
    { name: 'Alexander Prass', nation: 'Austria', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Marcel Sabitzer', nation: 'Austria', age: 29, position: 'Midfielder', difficulty: 3 },
    { name: 'Romano Schmid', nation: 'Austria', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Matthias Seidl', nation: 'Austria', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Nicolas Seiwald', nation: 'Austria', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Marko Arnautović', nation: 'Austria', age: 34, position: 'Striker', difficulty: 2 },
    { name: 'Maximilian Entrup', nation: 'Austria', age: 26, position: 'Striker', difficulty: 3 },
    { name: 'Michael Gregoritsch', nation: 'Austria', age: 29, position: 'Striker', difficulty: 3 },
    { name: 'Andreas Weimann', nation: 'Austria', age: 32, position: 'Striker', difficulty: 3 },


    // Adding Belgian players
    { name: 'Koen Casteels', nation: 'Belgium', age: 31, position: 'Goalie', difficulty: 2 },
    { name: 'Thomas Kaminski', nation: 'Belgium', age: 30, position: 'Goalie', difficulty: 2 },
    { name: 'Matz Sels', nation: 'Belgium', age: 32, position: 'Goalie', difficulty: 2 },
    { name: 'Timothy Castagne', nation: 'Belgium', age: 28, position: 'Right Back', difficulty: 2 },
    { name: 'Zeno Debast', nation: 'Belgium', age: 20, position: 'Center Back', difficulty: 2 },
    { name: 'Wout Faes', nation: 'Belgium', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Thomas Meunier', nation: 'Belgium', age: 32, position: 'Right Back', difficulty: 2 },
    { name: 'Arthur Theate', nation: 'Belgium', age: 23, position: 'Center Back', difficulty: 2 },
    { name: 'Jan Vertonghen', nation: 'Belgium', age: 36, position: 'Center Back', difficulty: 1 },
    { name: 'Maxim De Cuyper', nation: 'Belgium', age: 23, position: 'Left Back', difficulty: 2 },
    { name: 'Orel Mangala', nation: 'Belgium', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Amadou Onana', nation: 'Belgium', age: 22, position: 'Midfielder', difficulty: 2 },
    { name: 'Youri Tielemans', nation: 'Belgium', age: 26, position: 'Midfielder', difficulty: 1 },
    { name: 'Leandro Trossard', nation: 'Belgium', age: 29, position: 'Left Wing', difficulty: 1 },
    { name: 'Arthur Vermeeren', nation: 'Belgium', age: 18, position: 'Midfielder', difficulty: 3 },
    { name: 'Aster Vranckx', nation: 'Belgium', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Axel Witsel', nation: 'Belgium', age: 34, position: 'Midfielder', difficulty: 1 },
    { name: 'Johan Bakayoko', nation: 'Belgium', age: 20, position: 'Right Wing', difficulty: 3 },
    { name: 'Yannick Carrasco', nation: 'Belgium', age: 30, position: 'Left Wing', difficulty: 1 },
    { name: 'Charles De Ketelaere', nation: 'Belgium', age: 22, position: 'Forward', difficulty: 2 },
    { name: 'Jérémy Doku', nation: 'Belgium', age: 21, position: 'Right Wing', difficulty: 2 },
    { name: 'Romelu Lukaku', nation: 'Belgium', age: 30, position: 'Striker', difficulty: 1 },
    { name: 'Dodi Lukebakio', nation: 'Belgium', age: 26, position: 'Right Wing', difficulty: 2 },
    { name: 'Loïs Openda', nation: 'Belgium', age: 23, position: 'Striker', difficulty: 2 },

    // Adding Croatian players
    { name: 'Ivica Ivušić', nation: 'Croatia', age: 28, position: 'Goalie', difficulty: 2 },
    { name: 'Nediljko Labrović', nation: 'Croatia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Dominik Livaković', nation: 'Croatia', age: 29, position: 'Goalie', difficulty: 1 },
    { name: 'Martin Erlić', nation: 'Croatia', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Joško Gvardiol', nation: 'Croatia', age: 22, position: 'Center Back', difficulty: 1 },
    { name: 'Josip Juranović', nation: 'Croatia', age: 28, position: 'Right Back', difficulty: 2 },
    { name: 'Marin Pongračić', nation: 'Croatia', age: 26, position: 'Center Back', difficulty: 3 },
    { name: 'Borna Sosa', nation: 'Croatia', age: 26, position: 'Left Back', difficulty: 2 },
    { name: 'Josip Stanišić', nation: 'Croatia', age: 23, position: 'Right Back', difficulty: 2 },
    { name: 'Josip Šutalo', nation: 'Croatia', age: 23, position: 'Center Back', difficulty: 2 },
    { name: 'Domagoj Vida', nation: 'Croatia', age: 34, position: 'Center Back', difficulty: 1 },
    { name: 'Martin Baturina', nation: 'Croatia', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Marcelo Brozović', nation: 'Croatia', age: 30, position: 'Midfielder', difficulty: 1 },
    { name: 'Mateo Kovačić', nation: 'Croatia', age: 29, position: 'Midfielder', difficulty: 1 },
    { name: 'Lovro Majer', nation: 'Croatia', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Luka Modrić', nation: 'Croatia', age: 38, position: 'Midfielder', difficulty: 1 },
    { name: 'Mario Pašalić', nation: 'Croatia', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Luka Sučić', nation: 'Croatia', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Nikola Vlašić', nation: 'Croatia', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Ante Budimir', nation: 'Croatia', age: 32, position: 'Striker', difficulty: 2 },
    { name: 'Luka Ivanušec', nation: 'Croatia', age: 24, position: 'Left Wing', difficulty: 2 },
    { name: 'Andrej Kramarić', nation: 'Croatia', age: 32, position: 'Striker', difficulty: 1 },
    { name: 'Marco Pašalić', nation: 'Croatia', age: 22, position: 'Right Wing', difficulty: 3 },
    { name: 'Ivan Perišić', nation: 'Croatia', age: 35, position: 'Left Wing', difficulty: 1 },
    { name: 'Bruno Petković', nation: 'Croatia', age: 28, position: 'Striker', difficulty: 2 },
    { name: 'Marko Pjaca', nation: 'Croatia', age: 28, position: 'Right Wing', difficulty: 2 },

    // Adding Czechia players
    { name: 'Vítězslav Jaroš', nation: 'Czechia', age: 22, position: 'Goalie', difficulty: 3 },
    { name: 'Matěj Kovář', nation: 'Czechia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Jindřich Staněk', nation: 'Czechia', age: 28, position: 'Goalie', difficulty: 3 },
    { name: 'Vladimír Coufal', nation: 'Czechia', age: 30, position: 'Right Back', difficulty: 1 },
    { name: 'David Douděra', nation: 'Czechia', age: 25, position: 'Right Back', difficulty: 3 },
    { name: 'Robin Hranáč', nation: 'Czechia', age: 22, position: 'Center Back', difficulty: 3 },
    { name: 'David Jurásek', nation: 'Czechia', age: 23, position: 'Left Back', difficulty: 3 },
    { name: 'Ladislav Krejčí', nation: 'Czechia', age: 24, position: 'Center Back', difficulty: 3 },
    { name: 'Martin Vitík', nation: 'Czechia', age: 20, position: 'Center Back', difficulty: 3 },
    { name: 'Tomáš Vlček', nation: 'Czechia', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'David Zima', nation: 'Czechia', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Antonín Barák', nation: 'Czechia', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Lukáš Červ', nation: 'Czechia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Tomáš Holeš', nation: 'Czechia', age: 30, position: 'Midfielder', difficulty: 2 },
    { name: 'Matěj Jurásek', nation: 'Czechia', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Ondřej Lingr', nation: 'Czechia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Lukáš Provod', nation: 'Czechia', age: 26, position: 'Midfielder', difficulty: 2 },
    { name: 'Michal Sadílek', nation: 'Czechia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Tomáš Souček', nation: 'Czechia', age: 28, position: 'Midfielder', difficulty: 1 },
    { name: 'Pavel Šulc', nation: 'Czechia', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Václav Černý', nation: 'Czechia', age: 25, position: 'Right Wing', difficulty: 2 },
    { name: 'Tomáš Chorý', nation: 'Czechia', age: 28, position: 'Striker', difficulty: 3 },
    { name: 'Mojmír Chytil', nation: 'Czechia', age: 24, position: 'Striker', difficulty: 3 },
    { name: 'Adam Hložek', nation: 'Czechia', age: 21, position: 'Forward', difficulty: 2 },
    { name: 'Jan Kuchta', nation: 'Czechia', age: 27, position: 'Striker', difficulty: 2 },
    { name: 'Patrik Schick', nation: 'Czechia', age: 28, position: 'Striker', difficulty: 1 },

    // Adding Danish players
    { name: 'Mads Hermansen', nation: 'Denmark', age: 23, position: 'Goalie', difficulty: 3 },
    { name: 'Frederik Rønnow', nation: 'Denmark', age: 31, position: 'Goalie', difficulty: 2 },
    { name: 'Kasper Schmeichel', nation: 'Denmark', age: 37, position: 'Goalie', difficulty: 1 },
    { name: 'Joachim Andersen', nation: 'Denmark', age: 27, position: 'Center Back', difficulty: 2 },
    { name: 'Alexander Bah', nation: 'Denmark', age: 25, position: 'Right Back', difficulty: 3 },
    { name: 'Andreas Christensen', nation: 'Denmark', age: 27, position: 'Center Back', difficulty: 1 },
    { name: 'Mathias Jørgensen', nation: 'Denmark', age: 33, position: 'Center Back', difficulty: 2 },
    { name: 'Simon Kjær', nation: 'Denmark', age: 34, position: 'Center Back', difficulty: 1 },
    { name: 'Rasmus Kristensen', nation: 'Denmark', age: 26, position: 'Right Back', difficulty: 2 },
    { name: 'Victor Kristiansen', nation: 'Denmark', age: 21, position: 'Left Back', difficulty: 3 },
    { name: 'Joakim Mæhle', nation: 'Denmark', age: 26, position: 'Left Back', difficulty: 2 },
    { name: 'Jannik Vestergaard', nation: 'Denmark', age: 31, position: 'Center Back', difficulty: 2 },
    { name: 'Jacob Bruun Larsen', nation: 'Denmark', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Thomas Delaney', nation: 'Denmark', age: 32, position: 'Midfielder', difficulty: 2 },
    { name: 'Anders Dreyer', nation: 'Denmark', age: 25, position: 'Midfielder', difficulty: 3 },
    { name: 'Christian Eriksen', nation: 'Denmark', age: 32, position: 'Midfielder', difficulty: 1 },
    { name: 'Morten Hjulmand', nation: 'Denmark', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Pierre-Emile Højbjerg', nation: 'Denmark', age: 28, position: 'Midfielder', difficulty: 1 },
    { name: 'Mathias Jensen', nation: 'Denmark', age: 27, position: 'Midfielder', difficulty: 2 },
    { name: 'Christian Nørgaard', nation: 'Denmark', age: 29, position: 'Midfielder', difficulty: 2 },
    { name: 'Mikkel Damsgaard', nation: 'Denmark', age: 23, position: 'Forward', difficulty: 2 },
    { name: 'Kasper Dolberg', nation: 'Denmark', age: 25, position: 'Striker', difficulty: 2 },
    { name: 'Rasmus Højlund', nation: 'Denmark', age: 20, position: 'Striker', difficulty: 1 },
    { name: 'Andreas Skov Olsen', nation: 'Denmark', age: 23, position: 'Right Wing', difficulty: 2 },
    { name: 'Yussuf Poulsen', nation: 'Denmark', age: 29, position: 'Striker', difficulty: 1 },
    { name: 'Jonas Wind', nation: 'Denmark', age: 24, position: 'Striker', difficulty: 2 },

    // Adding English players
    { name: 'Dean Henderson', nation: 'England', age: 26, position: 'Goalie', difficulty: 2 },
    { name: 'Jordan Pickford', nation: 'England', age: 30, position: 'Goalie', difficulty: 1 },
    { name: 'Aaron Ramsdale', nation: 'England', age: 25, position: 'Goalie', difficulty: 1 },
    { name: 'Trent Alexander-Arnold', nation: 'England', age: 25, position: 'Right Back', difficulty: 1 },
    { name: 'Lewis Dunk', nation: 'England', age: 32, position: 'Center Back', difficulty: 2 },
    { name: 'Joe Gomez', nation: 'England', age: 26, position: 'Center Back', difficulty: 2 },
    { name: 'Marc Guéhi', nation: 'England', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Ezri Konsa', nation: 'England', age: 25, position: 'Center Back', difficulty: 3 },
    { name: 'Luke Shaw', nation: 'England', age: 28, position: 'Left Back', difficulty: 1 },
    { name: 'John Stones', nation: 'England', age: 29, position: 'Center Back', difficulty: 1 },
    { name: 'Kieran Trippier', nation: 'England', age: 33, position: 'Right Back', difficulty: 1 },
    { name: 'Kyle Walker', nation: 'England', age: 34, position: 'Right Back', difficulty: 1 },
    { name: 'Jude Bellingham', nation: 'England', age: 20, position: 'Midfielder', difficulty: 1 },
    { name: 'Phil Foden', nation: 'England', age: 24, position: 'Midfielder', difficulty: 1 },
    { name: 'Conor Gallagher', nation: 'England', age: 23, position: 'Midfielder', difficulty: 2 },
    { name: 'Kobbie Mainoo', nation: 'England', age: 18, position: 'Midfielder', difficulty: 3 },
    { name: 'Cole Palmer', nation: 'England', age: 21, position: 'Midfielder', difficulty: 2 },
    { name: 'Declan Rice', nation: 'England', age: 25, position: 'Midfielder', difficulty: 1 },
    { name: 'Adam Wharton', nation: 'England', age: 19, position: 'Midfielder', difficulty: 3 },
    { name: 'Jarrod Bowen', nation: 'England', age: 27, position: 'Right Wing', difficulty: 2 },
    { name: 'Eberechi Eze', nation: 'England', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Anthony Gordon', nation: 'England', age: 23, position: 'Left Wing', difficulty: 2 },
    { name: 'Harry Kane', nation: 'England', age: 30, position: 'Striker', difficulty: 1 },
    { name: 'Bukayo Saka', nation: 'England', age: 22, position: 'Right Wing', difficulty: 1 },
    { name: 'Ivan Toney', nation: 'England', age: 27, position: 'Striker', difficulty: 2 },
    { name: 'Ollie Watkins', nation: 'England', age: 27, position: 'Striker', difficulty: 2 },

    // Adding French players
    { name: 'Alphonse Areola', nation: 'France', age: 30, position: 'Goalie', difficulty: 2 },
    { name: 'Mike Maignan', nation: 'France', age: 28, position: 'Goalie', difficulty: 1 },
    { name: 'Brice Samba', nation: 'France', age: 29, position: 'Goalie', difficulty: 2 },
    { name: 'Jonathan Clauss', nation: 'France', age: 31, position: 'Right Back', difficulty: 3 },
    { name: 'Theo Hernández', nation: 'France', age: 26, position: 'Left Back', difficulty: 1 },
    { name: 'Ibrahima Konaté', nation: 'France', age: 24, position: 'Center Back', difficulty: 2 },
    { name: 'Jules Koundé', nation: 'France', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Ferland Mendy', nation: 'France', age: 28, position: 'Left Back', difficulty: 2 },
    { name: 'Benjamin Pavard', nation: 'France', age: 27, position: 'Right Back', difficulty: 1 },
    { name: 'William Saliba', nation: 'France', age: 22, position: 'Center Back', difficulty: 2 },
    { name: 'Dayot Upamecano', nation: 'France', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Eduardo Camavinga', nation: 'France', age: 21, position: 'Midfielder', difficulty: 1 },
    { name: 'Youssouf Fofana', nation: 'France', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Antoine Griezmann', nation: 'France', age: 32, position: 'Forward', difficulty: 1 },
    { name: 'N\'Golo Kanté', nation: 'France', age: 32, position: 'Midfielder', difficulty: 1 },
    { name: 'Adrien Rabiot', nation: 'France', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Aurélien Tchouameni', nation: 'France', age: 23, position: 'Midfielder', difficulty: 1 },
    { name: 'Warren Zaïre-Emery', nation: 'France', age: 17, position: 'Midfielder', difficulty: 3 },
    { name: 'Bradley Barcola', nation: 'France', age: 21, position: 'Forward', difficulty: 3 },
    { name: 'Kingsley Coman', nation: 'France', age: 27, position: 'Right Wing', difficulty: 1 },
    { name: 'Ousmane Dembélé', nation: 'France', age: 26, position: 'Right Wing', difficulty: 1 },
    { name: 'Olivier Giroud', nation: 'France', age: 37, position: 'Striker', difficulty: 1 },
    { name: 'Randal Kolo Muani', nation: 'France', age: 25, position: 'Striker', difficulty: 2 },
    { name: 'Kylian Mbappé', nation: 'France', age: 25, position: 'Right Wing', difficulty: 1 },
    { name: 'Marcus Thuram', nation: 'France', age: 26, position: 'Striker', difficulty: 2 },

        // Adding Georgian players
    { name: 'Luka Gugeshashvili', nation: 'Georgia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Giorgi Loria', nation: 'Georgia', age: 37, position: 'Goalie', difficulty: 3 },
    { name: 'Giorgi Mamardashvili', nation: 'Georgia', age: 23, position: 'Goalie', difficulty: 3 },
    { name: 'Lasha Dvali', nation: 'Georgia', age: 28, position: 'Center Back', difficulty: 3 },
    { name: 'Giorgi Gocholeishvili', nation: 'Georgia', age: 22, position: 'Right Back', difficulty: 3 },
    { name: 'Giorgi Gvelesiani', nation: 'Georgia', age: 32, position: 'Center Back', difficulty: 3 },
    { name: 'Otar Kakabadze', nation: 'Georgia', age: 28, position: 'Right Back', difficulty: 3 },
    { name: 'Guram Kashia', nation: 'Georgia', age: 35, position: 'Center Back', difficulty: 3 },
    { name: 'Solomon Kverkvelia', nation: 'Georgia', age: 31, position: 'Center Back', difficulty: 3 },
    { name: 'Luka Lochoshvili', nation: 'Georgia', age: 25, position: 'Center Back', difficulty: 3 },
    { name: 'Jemal Tabidze', nation: 'Georgia', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Sandro Altunashvili', nation: 'Georgia', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Chakvetadze', nation: 'Georgia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Zuriko Davitashvili', nation: 'Georgia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Otar Kiteishvili', nation: 'Georgia', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Kochorashvili', nation: 'Georgia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Nika Kvekveskiri', nation: 'Georgia', age: 31, position: 'Midfielder', difficulty: 3 },
    { name: 'Saba Lobjanidze', nation: 'Georgia', age: 28, position: 'Midfielder', difficulty: 3 },
    { name: 'Anzor Mekvabishvili', nation: 'Georgia', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Gabriel Sigua', nation: 'Georgia', age: 18, position: 'Midfielder', difficulty: 3 },
    { name: 'Levan Shengelia', nation: 'Georgia', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Tsitaishvili', nation: 'Georgia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Khvicha Kvaratskhelia', nation: 'Georgia', age: 22, position: 'Left Wing', difficulty: 1 },
    { name: 'Giorgi Kvilitaia', nation: 'Georgia', age: 30, position: 'Striker', difficulty: 3 },
    { name: 'Georges Mikautadze', nation: 'Georgia', age: 23, position: 'Striker', difficulty: 3 },
    { name: 'Budu Zivzivadze', nation: 'Georgia', age: 29, position: 'Striker', difficulty: 3 },


    // Adding German players
    { name: 'Oliver Baumann', nation: 'Germany', age: 33, position: 'Goalie', difficulty: 2 },
    { name: 'Manuel Neuer', nation: 'Germany', age: 38, position: 'Goalie', difficulty: 1 },
    { name: 'Marc-André ter Stegen', nation: 'Germany', age: 32, position: 'Goalie', difficulty: 1 },
    { name: 'Waldemar Anton', nation: 'Germany', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Benjamin Henrichs', nation: 'Germany', age: 26, position: 'Right Back', difficulty: 2 },
    { name: 'Joshua Kimmich', nation: 'Germany', age: 28, position: 'Right Back', difficulty: 1 },
    { name: 'Robin Koch', nation: 'Germany', age: 26, position: 'Center Back', difficulty: 2 },
    { name: 'Maximilian Mittelstädt', nation: 'Germany', age: 26, position: 'Left Back', difficulty: 3 },
    { name: 'David Raum', nation: 'Germany', age: 25, position: 'Left Back', difficulty: 2 },
    { name: 'Antonio Rüdiger', nation: 'Germany', age: 30, position: 'Center Back', difficulty: 1 },
    { name: 'Nico Schlotterbeck', nation: 'Germany', age: 24, position: 'Center Back', difficulty: 2 },
    { name: 'Jonathan Tah', nation: 'Germany', age: 27, position: 'Center Back', difficulty: 2 },
    { name: 'Robert Andrich', nation: 'Germany', age: 29, position: 'Midfielder', difficulty: 3 },
    { name: 'Chris Führich', nation: 'Germany', age: 25, position: 'Midfielder', difficulty: 3 },
    { name: 'İlkay Gündoğan', nation: 'Germany', age: 33, position: 'Midfielder', difficulty: 1 },
    { name: 'Pascal Gross', nation: 'Germany', age: 33, position: 'Midfielder', difficulty: 2 },
    { name: 'Toni Kroos', nation: 'Germany', age: 34, position: 'Midfielder', difficulty: 1 },
    { name: 'Jamal Musiala', nation: 'Germany', age: 21, position: 'Midfielder', difficulty: 1 },
    { name: 'Aleksandar Pavlović', nation: 'Germany', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Leroy Sané', nation: 'Germany', age: 28, position: 'Right Wing', difficulty: 1 },
    { name: 'Florian Wirtz', nation: 'Germany', age: 21, position: 'Midfielder', difficulty: 1 },
    { name: 'Maximilian Beier', nation: 'Germany', age: 21, position: 'Forward', difficulty: 3 },
    { name: 'Niclas Füllkrug', nation: 'Germany', age: 30, position: 'Striker', difficulty: 2 },
    { name: 'Kai Havertz', nation: 'Germany', age: 24, position: 'Forward', difficulty: 1 },
    { name: 'Thomas Müller', nation: 'Germany', age: 34, position: 'Forward', difficulty: 1 },
    { name: 'Deniz Undav', nation: 'Germany', age: 27, position: 'Forward', difficulty: 3 },

// Adding Italian players
{ name: 'Gianluigi Donnarumma', nation: 'Italy', age: 25, position: 'Goalie', difficulty: 1 },
{ name: 'Alex Meret', nation: 'Italy', age: 26, position: 'Goalie', difficulty: 2 },
{ name: 'Guglielmo Vicario', nation: 'Italy', age: 27, position: 'Goalie', difficulty: 2 },
{ name: 'Alessandro Bastoni', nation: 'Italy', age: 24, position: 'Center Back', difficulty: 1 },
{ name: 'Raoul Bellanova', nation: 'Italy', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Alessandro Buongiorno', nation: 'Italy', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Riccardo Calafiori', nation: 'Italy', age: 21, position: 'Left Back', difficulty: 3 },
{ name: 'Andrea Cambiaso', nation: 'Italy', age: 23, position: 'Left Back', difficulty: 3 },
{ name: 'Matteo Darmian', nation: 'Italy', age: 34, position: 'Right Back', difficulty: 2 },
{ name: 'Giovanni Di Lorenzo', nation: 'Italy', age: 30, position: 'Right Back', difficulty: 1 },
{ name: 'Federico Dimarco', nation: 'Italy', age: 25, position: 'Left Back', difficulty: 2 },
{ name: 'Federico Gatti', nation: 'Italy', age: 25, position: 'Center Back', difficulty: 3 },
{ name: 'Gianluca Mancini', nation: 'Italy', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Nicolò Barella', nation: 'Italy', age: 26, position: 'Midfielder', difficulty: 1 },
{ name: 'Bryan Cristante', nation: 'Italy', age: 28, position: 'Midfielder', difficulty: 2 },
{ name: 'Nicolò Fagioli', nation: 'Italy', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Davide Frattesi', nation: 'Italy', age: 24, position: 'Midfielder', difficulty: 2 },
{ name: 'Jorginho', nation: 'Italy', age: 32, position: 'Midfielder', difficulty: 1 },
{ name: 'Lorenzo Pellegrini', nation: 'Italy', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Federico Chiesa', nation: 'Italy', age: 26, position: 'Right Wing', difficulty: 1 },
{ name: 'Stephan El Shaarawy', nation: 'Italy', age: 31, position: 'Left Wing', difficulty: 2 },
{ name: 'Michael Folorunsho', nation: 'Italy', age: 25, position: 'Forward', difficulty: 3 },
{ name: 'Giacomo Raspadori', nation: 'Italy', age: 23, position: 'Forward', difficulty: 2 },
{ name: 'Mateo Retegui', nation: 'Italy', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Gianluca Scamacca', nation: 'Italy', age: 24, position: 'Striker', difficulty: 2 },
{ name: 'Mattia Zaccagni', nation: 'Italy', age: 28, position: 'Left Wing', difficulty: 3 },

// Adding Netherlands players
{ name: 'Justin Bijlow', nation: 'Netherlands', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Mark Flekken', nation: 'Netherlands', age: 30, position: 'Goalie', difficulty: 3 },
{ name: 'Bart Verbruggen', nation: 'Netherlands', age: 21, position: 'Goalie', difficulty: 3 },
{ name: 'Nathan Aké', nation: 'Netherlands', age: 29, position: 'Center Back', difficulty: 1 },
{ name: 'Daley Blind', nation: 'Netherlands', age: 34, position: 'Left Back', difficulty: 1 },
{ name: 'Matthijs de Ligt', nation: 'Netherlands', age: 24, position: 'Center Back', difficulty: 1 },
{ name: 'Stefan de Vrij', nation: 'Netherlands', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Denzel Dumfries', nation: 'Netherlands', age: 28, position: 'Right Back', difficulty: 1 },
{ name: 'Lutsharel Geertruida', nation: 'Netherlands', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Micky van de Ven', nation: 'Netherlands', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Virgil van Dijk', nation: 'Netherlands', age: 32, position: 'Center Back', difficulty: 1 },
{ name: 'Frenkie de Jong', nation: 'Netherlands', age: 26, position: 'Midfielder', difficulty: 1 },
{ name: 'Ryan Gravenberch', nation: 'Netherlands', age: 21, position: 'Midfielder', difficulty: 2 },
{ name: 'Teun Koopmeiners', nation: 'Netherlands', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'Tijjani Reijnders', nation: 'Netherlands', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Jerdy Schouten', nation: 'Netherlands', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Joey Veerman', nation: 'Netherlands', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Georginio Wijnaldum', nation: 'Netherlands', age: 33, position: 'Midfielder', difficulty: 1 },
{ name: 'Steven Bergwijn', nation: 'Netherlands', age: 26, position: 'Left Wing', difficulty: 2 },
{ name: 'Brian Brobbey', nation: 'Netherlands', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Memphis Depay', nation: 'Netherlands', age: 29, position: 'Left Wing', difficulty: 1 },
{ name: 'Jeremie Frimpong', nation: 'Netherlands', age: 22, position: 'Right Wing', difficulty: 3 },
{ name: 'Cody Gakpo', nation: 'Netherlands', age: 24, position: 'Forward', difficulty: 1 },
{ name: 'Donyell Malen', nation: 'Netherlands', age: 24, position: 'Right Wing', difficulty: 2 },
{ name: 'Xavi Simons', nation: 'Netherlands', age: 20, position: 'Midfielder', difficulty: 3 },
{ name: 'Wout Weghorst', nation: 'Netherlands', age: 31, position: 'Striker', difficulty: 2 },

// Adding Polish players
{ name: 'Marcin Bulka', nation: 'Poland', age: 24, position: 'Goalie', difficulty: 3 },
{ name: 'Łukasz Skorupski', nation: 'Poland', age: 32, position: 'Goalie', difficulty: 2 },
{ name: 'Wojciech Szczęsny', nation: 'Poland', age: 34, position: 'Goalie', difficulty: 1 },
{ name: 'Jan Bednarek', nation: 'Poland', age: 28, position: 'Center Back', difficulty: 2 },
{ name: 'Bartosz Bereszyński', nation: 'Poland', age: 31, position: 'Right Back', difficulty: 2 },
{ name: 'Przemysław Frankowski', nation: 'Poland', age: 28, position: 'Right Back', difficulty: 2 },
{ name: 'Jakub Kiwior', nation: 'Poland', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Tymoteusz Puchacz', nation: 'Poland', age: 24, position: 'Left Back', difficulty: 3 },
{ name: 'Bartosz Salamon', nation: 'Poland', age: 32, position: 'Center Back', difficulty: 3 },
{ name: 'Sebastian Walukiewicz', nation: 'Poland', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Paweł Dawidowicz', nation: 'Poland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Kamil Grosicki', nation: 'Poland', age: 35, position: 'Left Wing', difficulty: 2 },
{ name: 'Jakub Moder', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Jakub Piotrowski', nation: 'Poland', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Taras Romanczuk', nation: 'Poland', age: 31, position: 'Midfielder', difficulty: 3 },
{ name: 'Bartosz Slisz', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Damian Szymański', nation: 'Poland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Sebastian Szymański', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 2 },
{ name: 'Kacper Urbański', nation: 'Poland', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'Nicola Zalewski', nation: 'Poland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Piotr Zieliński', nation: 'Poland', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Adam Buksa', nation: 'Poland', age: 27, position: 'Striker', difficulty: 3 },
{ name: 'Robert Lewandowski', nation: 'Poland', age: 35, position: 'Striker', difficulty: 1 },
{ name: 'Krzysztof Piątek', nation: 'Poland', age: 28, position: 'Striker', difficulty: 2 },
{ name: 'Michał Skóraś', nation: 'Poland', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Karol Świderski', nation: 'Poland', age: 27, position: 'Striker', difficulty: 3 },

// Adding Portuguese players
{ name: 'Diogo Costa', nation: 'Portugal', age: 24, position: 'Goalie', difficulty: 2 },
{ name: 'Rui Patrício', nation: 'Portugal', age: 35, position: 'Goalie', difficulty: 1 },
{ name: 'José Sá', nation: 'Portugal', age: 31, position: 'Goalie', difficulty: 2 },
{ name: 'João Cancelo', nation: 'Portugal', age: 29, position: 'Right Back', difficulty: 1 },
{ name: 'Diogo Dalot', nation: 'Portugal', age: 25, position: 'Right Back', difficulty: 2 },
{ name: 'Rúben Dias', nation: 'Portugal', age: 26, position: 'Center Back', difficulty: 1 },
{ name: 'Gonçalo Inácio', nation: 'Portugal', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Nuno Mendes', nation: 'Portugal', age: 21, position: 'Left Back', difficulty: 1 },
{ name: 'Pepe', nation: 'Portugal', age: 40, position: 'Center Back', difficulty: 1 },
{ name: 'Nélson Semedo', nation: 'Portugal', age: 30, position: 'Right Back', difficulty: 2 },
{ name: 'António Silva', nation: 'Portugal', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Danilo', nation: 'Portugal', age: 32, position: 'Midfielder', difficulty: 2 },
{ name: 'Bruno Fernandes', nation: 'Portugal', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Pedro Neto', nation: 'Portugal', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'João Neves', nation: 'Portugal', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'Rúben Neves', nation: 'Portugal', age: 26, position: 'Midfielder', difficulty: 2 },
{ name: 'Matheus Nunes', nation: 'Portugal', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'João Palhinha', nation: 'Portugal', age: 28, position: 'Midfielder', difficulty: 2 },
{ name: 'Bernardo Silva', nation: 'Portugal', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Vitinha', nation: 'Portugal', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'Francisco Conceição', nation: 'Portugal', age: 21, position: 'Right Wing', difficulty: 3 },
{ name: 'João Félix', nation: 'Portugal', age: 24, position: 'Forward', difficulty: 1 },
{ name: 'Diogo Jota', nation: 'Portugal', age: 27, position: 'Left Wing', difficulty: 1 },
{ name: 'Rafael Leão', nation: 'Portugal', age: 24, position: 'Left Wing', difficulty: 2 },
{ name: 'Gonçalo Ramos', nation: 'Portugal', age: 22, position: 'Striker', difficulty: 2 },
{ name: 'Cristiano Ronaldo', nation: 'Portugal', age: 39, position: 'Striker', difficulty: 1 },

// Adding Romanian players
{ name: 'Horațiu Moldovan', nation: 'Romania', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Florin Niță', nation: 'Romania', age: 36, position: 'Goalie', difficulty: 3 },
{ name: 'Ștefan Târnovanu', nation: 'Romania', age: 23, position: 'Goalie', difficulty: 3 },
{ name: 'Nicușor Bancu', nation: 'Romania', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'Andrei Burcă', nation: 'Romania', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'Radu Drăguşin', nation: 'Romania', age: 21, position: 'Center Back', difficulty: 3 },
{ name: 'Vasile Mogoş', nation: 'Romania', age: 30, position: 'Right Back', difficulty: 3 },
{ name: 'Ionuț Nedelcearu', nation: 'Romania', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Bogdan Racovițan', nation: 'Romania', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Andrei Rațiu', nation: 'Romania', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Adrian Rus', nation: 'Romania', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Alexandru Cicâldău', nation: 'Romania', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Ianis Hagi', nation: 'Romania', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Marius Marin', nation: 'Romania', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Răzvan Marin', nation: 'Romania', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Darius Olaru', nation: 'Romania', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Deian Sorescu', nation: 'Romania', age: 26, position: 'Right Wing', difficulty: 3 },
{ name: 'Nicolae Stanciu', nation: 'Romania', age: 30, position: 'Midfielder', difficulty: 3 },
{ name: 'Adrian Şut', nation: 'Romania', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Denis Alibec', nation: 'Romania', age: 32, position: 'Striker', difficulty: 3 },
{ name: 'Daniel Bîrligea', nation: 'Romania', age: 23, position: 'Striker', difficulty: 3 },
{ name: 'Florinel Coman', nation: 'Romania', age: 25, position: 'Left Wing', difficulty: 3 },
{ name: 'Denis Drăguş', nation: 'Romania', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Dennis Man', nation: 'Romania', age: 25, position: 'Right Wing', difficulty: 3 },
{ name: 'Valentin Mihăilă', nation: 'Romania', age: 24, position: 'Left Wing', difficulty: 3 },
{ name: 'George Puşcaş', nation: 'Romania', age: 28, position: 'Striker', difficulty: 3 },


// Adding Scottish players
{ name: 'Zander Clark', nation: 'Scotland', age: 31, position: 'Goalie', difficulty: 3 },
{ name: 'Angus Gunn', nation: 'Scotland', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Liam Kelly', nation: 'Scotland', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Liam Cooper', nation: 'Scotland', age: 32, position: 'Center Back', difficulty: 3 },
{ name: 'Grant Hanley', nation: 'Scotland', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Jack Hendry', nation: 'Scotland', age: 28, position: 'Center Back', difficulty: 3 },
{ name: 'Ross McCrorie', nation: 'Scotland', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Scott McKenna', nation: 'Scotland', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Ryan Porteous', nation: 'Scotland', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Anthony Ralston', nation: 'Scotland', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Andrew Robertson', nation: 'Scotland', age: 30, position: 'Left Back', difficulty: 1 },
{ name: 'Greg Taylor', nation: 'Scotland', age: 25, position: 'Left Back', difficulty: 3 },
{ name: 'Kieran Tierney', nation: 'Scotland', age: 27, position: 'Left Back', difficulty: 1 },
{ name: 'Stuart Armstrong', nation: 'Scotland', age: 31, position: 'Midfielder', difficulty: 2 },
{ name: 'James Forrest', nation: 'Scotland', age: 32, position: 'Right Wing', difficulty: 2 },
{ name: 'Billy Gilmour', nation: 'Scotland', age: 22, position: 'Midfielder', difficulty: 2 },
{ name: 'Ryan Jack', nation: 'Scotland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'John McGinn', nation: 'Scotland', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Callum McGregor', nation: 'Scotland', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Kenny McLean', nation: 'Scotland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Scott McTominay', nation: 'Scotland', age: 27, position: 'Midfielder', difficulty: 1 },
{ name: 'Lewis Morgan', nation: 'Scotland', age: 27, position: 'Right Wing', difficulty: 3 },
{ name: 'Ché Adams', nation: 'Scotland', age: 27, position: 'Striker', difficulty: 2 },
{ name: 'Ryan Christie', nation: 'Scotland', age: 28, position: 'Right Wing', difficulty: 2 },
{ name: 'Tommy Conway', nation: 'Scotland', age: 21, position: 'Forward', difficulty: 3 },
{ name: 'Lawrence Shankland', nation: 'Scotland', age: 28, position: 'Striker', difficulty: 3 },

// Adding Serbian players
{ name: 'Vanja Milinković-Savić', nation: 'Serbia', age: 26, position: 'Goalie', difficulty: 3 },
{ name: 'Đorđe Petrović', nation: 'Serbia', age: 23, position: 'Goalie', difficulty: 3 },
{ name: 'Predrag Rajković', nation: 'Serbia', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Srđan Babić', nation: 'Serbia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Nikola Milenković', nation: 'Serbia', age: 26, position: 'Center Back', difficulty: 2 },
{ name: 'Filip Mladenović', nation: 'Serbia', age: 32, position: 'Left Back', difficulty: 3 },
{ name: 'Strahinja Pavlović', nation: 'Serbia', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Uroš Spajić', nation: 'Serbia', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'Nemanja Stojić', nation: 'Serbia', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Miloš Veljković', nation: 'Serbia', age: 28, position: 'Center Back', difficulty: 3 },
{ name: 'Veljko Birmančević', nation: 'Serbia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Mijat Gaćinović', nation: 'Serbia', age: 29, position: 'Midfielder', difficulty: 3 },
{ name: 'Nemanja Gudelj', nation: 'Serbia', age: 32, position: 'Midfielder', difficulty: 2 },
{ name: 'Ivan Ilić', nation: 'Serbia', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Saša Lukić', nation: 'Serbia', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Nemanja Maksimović', nation: 'Serbia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Srdjan Mijailović', nation: 'Serbia', age: 30, position: 'Midfielder', difficulty: 3 },
{ name: 'Sergej Milinković-Savić', nation: 'Serbia', age: 28, position: 'Midfielder', difficulty: 2 },
{ name: 'Lazar Vujadin Samardžić', nation: 'Serbia', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Luka Jović', nation: 'Serbia', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Filip Kostić', nation: 'Serbia', age: 30, position: 'Left Wing', difficulty: 2 },
{ name: 'Aleksandar Mitrović', nation: 'Serbia', age: 29, position: 'Striker', difficulty: 1 },
{ name: 'Petar Ratkov', nation: 'Serbia', age: 20, position: 'Striker', difficulty: 3 },
{ name: 'Dušan Tadić', nation: 'Serbia', age: 35, position: 'Right Wing', difficulty: 1 },
{ name: 'Dušan Vlahović', nation: 'Serbia', age: 24, position: 'Striker', difficulty: 1 },
{ name: 'Andrija Živković', nation: 'Serbia', age: 27, position: 'Right Wing', difficulty: 3 },

// Adding Slovakian players
{ name: 'Martin Dúbravka', nation: 'Slovakia', age: 35, position: 'Goalie', difficulty: 2 },
{ name: 'Henrich Ravas', nation: 'Slovakia', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Marek Rodák', nation: 'Slovakia', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Vernon De Marco', nation: 'Slovakia', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'Norbert Gyömbér', nation: 'Slovakia', age: 31, position: 'Center Back', difficulty: 3 },
{ name: 'Dávid Hancko', nation: 'Slovakia', age: 25, position: 'Left Back', difficulty: 3 },
{ name: 'Sebastián Kóša', nation: 'Slovakia', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Adam Obert', nation: 'Slovakia', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Peter Pekarík', nation: 'Slovakia', age: 36, position: 'Right Back', difficulty: 2 },
{ name: 'Milan Škriniar', nation: 'Slovakia', age: 28, position: 'Center Back', difficulty: 1 },
{ name: 'Denis Vavro', nation: 'Slovakia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'László Bénes', nation: 'Slovakia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Matúš Bero', nation: 'Slovakia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Ondrej Duda', nation: 'Slovakia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Patrik Hrošovský', nation: 'Slovakia', age: 31, position: 'Midfielder', difficulty: 3 },
{ name: 'Juraj Kucka', nation: 'Slovakia', age: 36, position: 'Midfielder', difficulty: 3 },
{ name: 'Stanislav Lobotka', nation: 'Slovakia', age: 29, position: 'Midfielder', difficulty: 2 },
{ name: 'Tomáš Rigo', nation: 'Slovakia', age: 20, position: 'Midfielder', difficulty: 3 },
{ name: 'Róbert Boženík', nation: 'Slovakia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Dávid Ďuriš', nation: 'Slovakia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Lukáš Haraslín', nation: 'Slovakia', age: 27, position: 'Left Wing', difficulty: 3 },
{ name: 'Leo Sauer', nation: 'Slovakia', age: 18, position: 'Left Wing', difficulty: 3 },
{ name: 'Ivan Schranz', nation: 'Slovakia', age: 30, position: 'Right Wing', difficulty: 3 },
{ name: 'David Strelec', nation: 'Slovakia', age: 22, position: 'Striker', difficulty: 3 },
{ name: 'Tomáš Suslov', nation: 'Slovakia', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Ľubomír Tupta', nation: 'Slovakia', age: 25, position: 'Striker', difficulty: 3 },

// Adding Slovenian players
{ name: 'Vid Belec', nation: 'Slovenia', age: 33, position: 'Goalie', difficulty: 3 },
{ name: 'Jan Oblak', nation: 'Slovenia', age: 31, position: 'Goalie', difficulty: 1 },
{ name: 'Igor Vekić', nation: 'Slovenia', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Jure Balkovec', nation: 'Slovenia', age: 29, position: 'Left Back', difficulty: 3 },
{ name: 'Jaka Bijol', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Miha Blažič', nation: 'Slovenia', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'David Brekalo', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Vanja Drkušić', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Erik Janža', nation: 'Slovenia', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'Žan Karničnik', nation: 'Slovenia', age: 27, position: 'Right Back', difficulty: 3 },
{ name: 'Jon Gorenc Stanković', nation: 'Slovenia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Petar Stojanović', nation: 'Slovenia', age: 28, position: 'Right Back', difficulty: 3 },
{ name: 'Timi Elšnik', nation: 'Slovenia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Adam Gnezda Čerin', nation: 'Slovenia', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Tomi Horvat', nation: 'Slovenia', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'Josip Iličić', nation: 'Slovenia', age: 35, position: 'Right Wing', difficulty: 2 },
{ name: 'Jasmin Kurtić', nation: 'Slovenia', age: 34, position: 'Midfielder', difficulty: 3 },
{ name: 'Sandi Lovrić', nation: 'Slovenia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Benjamin Verbič', nation: 'Slovenia', age: 29, position: 'Left Wing', difficulty: 3 },
{ name: 'Adrian Zeljković', nation: 'Slovenia', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Nino Žugelj', nation: 'Slovenia', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'Žan Celar', nation: 'Slovenia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Jan Mlakar', nation: 'Slovenia', age: 25, position: 'Striker', difficulty: 3 },
{ name: 'Benjamin Šeško', nation: 'Slovenia', age: 20, position: 'Striker', difficulty: 2 },
{ name: 'Andraž Šporar', nation: 'Slovenia', age: 30, position: 'Striker', difficulty: 3 },
{ name: 'Žan Vipotnik', nation: 'Slovenia', age: 21, position: 'Striker', difficulty: 3 },

// Adding Spanish players
{ name: 'David Raya', nation: 'Spain', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Alejandro Remiro', nation: 'Spain', age: 28, position: 'Goalie', difficulty: 3 },
{ name: 'Unai Simón', nation: 'Spain', age: 26, position: 'Goalie', difficulty: 1 },
{ name: 'Dani Carvajal', nation: 'Spain', age: 32, position: 'Right Back', difficulty: 1 },
{ name: 'Marc Cucurella', nation: 'Spain', age: 25, position: 'Left Back', difficulty: 2 },
{ name: 'Alejandro Grimaldo', nation: 'Spain', age: 28, position: 'Left Back', difficulty: 2 },
{ name: 'Aymeric Laporte', nation: 'Spain', age: 29, position: 'Center Back', difficulty: 1 },
{ name: 'Robin Le Normand', nation: 'Spain', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Nacho', nation: 'Spain', age: 34, position: 'Center Back', difficulty: 2 },
{ name: 'Daniel Vivian', nation: 'Spain', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Álex Baena', nation: 'Spain', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Mikel Merino', nation: 'Spain', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Mikel Oyarzabal', nation: 'Spain', age: 26, position: 'Midfielder', difficulty: 2 },
{ name: 'Pedri', nation: 'Spain', age: 21, position: 'Midfielder', difficulty: 1 },
{ name: 'Rodri', nation: 'Spain', age: 27, position: 'Midfielder', difficulty: 1 },
{ name: 'Fabián Ruiz', nation: 'Spain', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Nico Williams', nation: 'Spain', age: 21, position: 'Right Wing', difficulty: 2 },
{ name: 'Martín Zubimendi', nation: 'Spain', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'Joselu', nation: 'Spain', age: 33, position: 'Striker', difficulty: 2 },
{ name: 'Fermín López', nation: 'Spain', age: 20, position: 'Midfielder', difficulty: 3 },
{ name: 'Álvaro Morata', nation: 'Spain', age: 31, position: 'Striker', difficulty: 1 },
{ name: 'Jesús Navas', nation: 'Spain', age: 38, position: 'Right Wing', difficulty: 1 },
{ name: 'Dani Olmo', nation: 'Spain', age: 26, position: 'Left Wing', difficulty: 2 },
{ name: 'Ayoze Pérez', nation: 'Spain', age: 30, position: 'Right Wing', difficulty: 3 },
{ name: 'Ferran Torres', nation: 'Spain', age: 23, position: 'Right Wing', difficulty: 2 },
{ name: 'Lamine Yamal', nation: 'Spain', age: 16, position: 'Right Wing', difficulty: 3 },

// Adding Swiss players
{ name: 'Gregor Kobel', nation: 'Switzerland', age: 26, position: 'Goalie', difficulty: 2 },
{ name: 'Yvon Mvogo', nation: 'Switzerland', age: 29, position: 'Goalie', difficulty: 3 },
{ name: 'Yann Sommer', nation: 'Switzerland', age: 35, position: 'Goalie', difficulty: 1 },
{ name: 'Manuel Akanji', nation: 'Switzerland', age: 28, position: 'Center Back', difficulty: 1 },
{ name: 'Nico Elvedi', nation: 'Switzerland', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Ricardo Rodríguez', nation: 'Switzerland', age: 31, position: 'Left Back', difficulty: 1 },
{ name: 'Fabian Schär', nation: 'Switzerland', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Leonidas Stergiou', nation: 'Switzerland', age: 21, position: 'Center Back', difficulty: 3 },
{ name: 'Silvan Widmer', nation: 'Switzerland', age: 31, position: 'Right Back', difficulty: 3 },
{ name: 'Cédric Zesiger', nation: 'Switzerland', age: 25, position: 'Center Back', difficulty: 3 },
{ name: 'Michel Aebischer', nation: 'Switzerland', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Remo Freuler', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 2 },
{ name: 'Ardon Jashari', nation: 'Switzerland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Fabian Rieder', nation: 'Switzerland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Xherdan Shaqiri', nation: 'Switzerland', age: 32, position: 'Right Wing', difficulty: 1 },
{ name: 'Vincent Sierro', nation: 'Switzerland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Renato Steffen', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Ruben Vargas', nation: 'Switzerland', age: 25, position: 'Right Wing', difficulty: 3 },
{ name: 'Granit Xhaka', nation: 'Switzerland', age: 31, position: 'Midfielder', difficulty: 1 },
{ name: 'Denis Zakaria', nation: 'Switzerland', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Steven Zuber', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Zeki Amdouni', nation: 'Switzerland', age: 23, position: 'Striker', difficulty: 3 },
{ name: 'Kwadwo Duah', nation: 'Switzerland', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Breel Embolo', nation: 'Switzerland', age: 27, position: 'Striker', difficulty: 1 },
{ name: 'Dan Ndoye', nation: 'Switzerland', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Noah Okafor', nation: 'Switzerland', age: 23, position: 'Left Wing', difficulty: 2 },

// Adding Turkish players
{ name: 'Altay Bayındır', nation: 'Türkiye', age: 25, position: 'Goalie', difficulty: 2 },
{ name: 'Mert Günok', nation: 'Türkiye', age: 34, position: 'Goalie', difficulty: 3 },
{ name: 'Uğurcan Çakır', nation: 'Türkiye', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Samet Akaydin', nation: 'Türkiye', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Abdülkerim Bardakcı', nation: 'Türkiye', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Zeki Çelik', nation: 'Türkiye', age: 26, position: 'Right Back', difficulty: 2 },
{ name: 'Merih Demiral', nation: 'Türkiye', age: 25, position: 'Center Back', difficulty: 2 },
{ name: 'Ferdi Kadıoğlu', nation: 'Türkiye', age: 23, position: 'Left Back', difficulty: 3 },
{ name: 'Ahmetcan Kaplan', nation: 'Türkiye', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Mert Müldür', nation: 'Türkiye', age: 24, position: 'Right Back', difficulty: 3 },
{ name: 'Hakan Çalhanoğlu', nation: 'Türkiye', age: 30, position: 'Midfielder', difficulty: 1 },
{ name: 'İsmail Yüksek', nation: 'Türkiye', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Kaan Ayhan', nation: 'Türkiye', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Okay Yokuşlu', nation: 'Türkiye', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Orkun Kökçü', nation: 'Türkiye', age: 22, position: 'Midfielder', difficulty: 2 },
{ name: 'Salih Özcan', nation: 'Türkiye', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Yunus Akgün', nation: 'Türkiye', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Kerem Aktürkoğlu', nation: 'Türkiye', age: 24, position: 'Left Wing', difficulty: 3 },
{ name: 'Arda Güler', nation: 'Türkiye', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'İrfan Can Kahveci', nation: 'Türkiye', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Semih Kılıçsoy', nation: 'Türkiye', age: 18, position: 'Forward', difficulty: 3 },
{ name: 'Cenk Tosun', nation: 'Türkiye', age: 32, position: 'Striker', difficulty: 2 },
{ name: 'Yusuf Yazıcı', nation: 'Türkiye', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Bertuğ Yıldırım', nation: 'Türkiye', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Kenan Yıldız', nation: 'Türkiye', age: 18, position: 'Midfielder', difficulty: 3 },
{ name: 'Barış Alper Yılmaz', nation: 'Türkiye', age: 23, position: 'Right Wing', difficulty: 3 },

// Adding Ukrainian players
{ name: 'Georgiy Bushchan', nation: 'Ukraine', age: 29, position: 'Goalie', difficulty: 3 },
{ name: 'Andriy Lunin', nation: 'Ukraine', age: 24, position: 'Goalie', difficulty: 2 },
{ name: 'Anatoliy Trubin', nation: 'Ukraine', age: 22, position: 'Goalie', difficulty: 3 },
{ name: 'Valeriy Bondar', nation: 'Ukraine', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Yukhym Konoplia', nation: 'Ukraine', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Mykola Matviyenko', nation: 'Ukraine', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Bogdan Mykhaylichenko', nation: 'Ukraine', age: 26, position: 'Left Back', difficulty: 3 },
{ name: 'Vitaliy Mykolenko', nation: 'Ukraine', age: 24, position: 'Left Back', difficulty: 2 },
{ name: 'Oleksandr Svatok', nation: 'Ukraine', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Maksym Talovierov', nation: 'Ukraine', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Oleksandr Tymchyk', nation: 'Ukraine', age: 26, position: 'Right Back', difficulty: 3 },
{ name: 'Illia Zabarnyi', nation: 'Ukraine', age: 21, position: 'Center Back', difficulty: 2 },
{ name: 'Oleksandr Zinchenko', nation: 'Ukraine', age: 27, position: 'Left Back', difficulty: 1 },
{ name: 'Volodymyr Brazhko', nation: 'Ukraine', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Ruslan Malinovskyi', nation: 'Ukraine', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Mykola Shaparenko', nation: 'Ukraine', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Taras Stepanenko', nation: 'Ukraine', age: 34, position: 'Midfielder', difficulty: 3 },
{ name: 'Georgiy Sudakov', nation: 'Ukraine', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Serhiy Sydorchuk', nation: 'Ukraine', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Viktor Tsygankov', nation: 'Ukraine', age: 26, position: 'Right Wing', difficulty: 2 },
{ name: 'Andriy Yarmolenko', nation: 'Ukraine', age: 34, position: 'Right Wing', difficulty: 2 },
{ name: 'Oleksandr Zubkov', nation: 'Ukraine', age: 26, position: 'Right Wing', difficulty: 3 },
{ name: 'Artem Dovbyk', nation: 'Ukraine', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Mykhailo Mudryk', nation: 'Ukraine', age: 23, position: 'Left Wing', difficulty: 2 },
{ name: 'Vladyslav Vanat', nation: 'Ukraine', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Roman Yaremchuk', nation: 'Ukraine', age: 28, position: 'Striker', difficulty: 2 },

  ];
  
  const groups = {
    A: ['Germany', 'Hungary', 'Scotland', 'Switzerland'],
    B: ['Spain', 'Croatia', 'Italy', 'Albania'],
    C: ['England', 'Denmark', 'Slovenia', 'Serbia'],
    D: ['France', 'Netherlands', 'Austria', 'Poland'],
    E: ['Belgium', 'Romania', 'Slovakia', 'Ukraine'],
    F: ['Portugal', 'Türkiye', 'Czechia', 'Georgia']
  };
  
  const positionGroups = {
    Forward: ['Left Wing', 'Striker', 'Right Wing'],
    Midfield: ['Defensive Midfield', 'Attacking Midfield', 'Midfielder'],
    Defense: ['Left Back', 'Center Back', 'Right Back'],
    Goalie: ['Goalie']
  };
  
  export { players, groups, positionGroups };
  