// src/players.js
const players = [

    // Albanian players
    { name: 'Etrit Berisha', nation: 'Albania', age: 34, position: 'Goalie', difficulty: 3 },
    { name: 'Elhan Kastrati', nation: 'Albania', age: 26, position: 'Goalie', difficulty: 3 },
    { name: 'Thomas Strakosha', nation: 'Albania', age: 29, position: 'Goalie', difficulty: 3 },
    { name: 'Arlind Ajeti', nation: 'Albania', age: 30, position: 'Center Back', difficulty: 3 },
    { name: 'Naser Aliji', nation: 'Albania', age: 29, position: 'Left Back', difficulty: 3 },
    { name: 'Ivan Balliu', nation: 'Albania', age: 32, position: 'Right Back', difficulty: 3 },
    { name: 'Berat Djimsiti', nation: 'Albania', age: 30, position: 'Center Back', difficulty: 3 },
    { name: 'Elseid Hysaj', nation: 'Albania', age: 30, position: 'Right Back', difficulty: 3 },
    { name: 'Ardian Ismajli', nation: 'Albania', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Marash Kumbulla', nation: 'Albania', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Enea Mihaj', nation: 'Albania', age: 24, position: 'Center Back', difficulty: 3 },
    { name: 'Mario Mitaj', nation: 'Albania', age: 20, position: 'Left Back', difficulty: 3 },
    { name: 'Amir Abrashi', nation: 'Albania', age: 33, position: 'Midfielder', difficulty: 3 },
    { name: 'Kristjan Asllani', nation: 'Albania', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Nedim Bajrami', nation: 'Albania', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Klaus Gjasula', nation: 'Albania', age: 33, position: 'Midfielder', difficulty: 3 },
    { name: 'Qazim Laci', nation: 'Albania', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Ylber Ramadani', nation: 'Albania', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Taulant Seferi', nation: 'Albania', age: 27, position: 'Striker', difficulty: 3 },
    { name: 'Jasir Asani', nation: 'Albania', age: 28, position: 'Right Wing', difficulty: 3 },
    { name: 'Medon Berisha', nation: 'Albania', age: 23, position: 'Striker', difficulty: 3 },
    { name: 'Armando Broja', nation: 'Albania', age: 22, position: 'Striker', difficulty: 3 },
    { name: 'Mirlind Daku', nation: 'Albania', age: 25, position: 'Striker', difficulty: 3 },
    { name: 'Arbër Hoxha', nation: 'Albania', age: 24, position: 'Left Wing', difficulty: 3 },
    { name: 'Rey Manaj', nation: 'Albania', age: 26, position: 'Striker', difficulty: 3 },
    { name: 'Ernest Muci', nation: 'Albania', age: 22, position: 'Striker', difficulty: 3 },

    // Adding Austrian players
    { name: 'Niklas Hedl', nation: 'Austria', age: 22, position: 'Goalie', difficulty: 3 },
    { name: 'Heinz Lindner', nation: 'Austria', age: 33, position: 'Goalie', difficulty: 3 },
    { name: 'Patrick Pentz', nation: 'Austria', age: 27, position: 'Goalie', difficulty: 3 },
    { name: 'Flavius Daniliuc', nation: 'Austria', age: 21, position: 'Center Back', difficulty: 3 },
    { name: 'Kevin Danso', nation: 'Austria', age: 25, position: 'Center Back', difficulty: 3 },
    { name: 'Philipp Lienhart', nation: 'Austria', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Phillipp Mwene', nation: 'Austria', age: 29, position: 'Right Back', difficulty: 3 },
    { name: 'Stefan Posch', nation: 'Austria', age: 26, position: 'Center Back', difficulty: 3 },
    { name: 'Leopold Querfeld', nation: 'Austria', age: 19, position: 'Center Back', difficulty: 3 },
    { name: 'Gernot Trauner', nation: 'Austria', age: 31, position: 'Center Back', difficulty: 3 },
    { name: 'Patrick Wimmer', nation: 'Austria', age: 22, position: 'Right Wing', difficulty: 3 },
    { name: 'Maximilian Wober', nation: 'Austria', age: 25, position: 'Left Back', difficulty: 3 },
    { name: 'Christoph Baumgartner', nation: 'Austria', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Florian Grillitsch', nation: 'Austria', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Marco Grull', nation: 'Austria', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Florian Kainz', nation: 'Austria', age: 31, position: 'Midfielder', difficulty: 3 },
    { name: 'Konrad Laimer', nation: 'Austria', age: 26, position: 'Defensive Midfield', difficulty: 2 },
    { name: 'Alexander Prass', nation: 'Austria', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Marcel Sabitzer', nation: 'Austria', age: 29, position: 'Midfielder', difficulty: 3 },
    { name: 'Romano Schmid', nation: 'Austria', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Matthias Seidl', nation: 'Austria', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Nicolas Seiwald', nation: 'Austria', age: 22, position: 'Defensive Midfield', difficulty: 3 },
    { name: 'Marko Arnautovic', nation: 'Austria', age: 34, position: 'Striker', difficulty: 2 },
    { name: 'Maximilian Entrup', nation: 'Austria', age: 26, position: 'Striker', difficulty: 3 },
    { name: 'Michael Gregoritsch', nation: 'Austria', age: 29, position: 'Striker', difficulty: 3 },
    { name: 'Andreas Weimann', nation: 'Austria', age: 32, position: 'Striker', difficulty: 3 },


    // Adding Belgian players
    { name: 'Koen Casteels', nation: 'Belgium', age: 31, position: 'Goalie', difficulty: 2 },
    { name: 'Thomas Kaminski', nation: 'Belgium', age: 31, position: 'Goalie', difficulty: 3 },
    { name: 'Matz Sels', nation: 'Belgium', age: 32, position: 'Goalie', difficulty: 2 },
    { name: 'Timothy Castagne', nation: 'Belgium', age: 28, position: 'Right Back', difficulty: 2 },
    { name: 'Zeno Debast', nation: 'Belgium', age: 20, position: 'Center Back', difficulty: 3 },
    { name: 'Wout Faes', nation: 'Belgium', age: 26, position: 'Center Back', difficulty: 2 },
    { name: 'Thomas Meunier', nation: 'Belgium', age: 32, position: 'Right Back', difficulty: 2 },
    { name: 'Arthur Theate', nation: 'Belgium', age: 24, position: 'Center Back', difficulty: 2 },
    { name: 'Jan Vertonghen', nation: 'Belgium', age: 37, position: 'Center Back', difficulty: 1 },
    { name: 'Maxim De Cuyper', nation: 'Belgium', age: 23, position: 'Left Back', difficulty: 2 },
    { name: 'Orel Mangala', nation: 'Belgium', age: 25, position: 'Defensive Midfield', difficulty: 2 },
    { name: 'Amadou Onana', nation: 'Belgium', age: 22, position: 'Midfielder', difficulty: 2 },
    { name: 'Youri Tielemans', nation: 'Belgium', age: 26, position: 'Midfielder', difficulty: 1 },
    { name: 'Leandro Trossard', nation: 'Belgium', age: 29, position: 'Left Wing', difficulty: 1 },
    { name: 'Arthur Vermeeren', nation: 'Belgium', age: 19, position: 'Midfielder', difficulty: 3 },
    { name: 'Aster Vranckx', nation: 'Belgium', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Axel Witsel', nation: 'Belgium', age: 35, position: 'Defensive Midfield', difficulty: 2 },
    { name: 'Kevin De Bruyne', nation: 'Belgium', age: 32, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Johan Bakayoko', nation: 'Belgium', age: 20, position: 'Right Wing', difficulty: 3 },
    { name: 'Yannick Carrasco', nation: 'Belgium', age: 30, position: 'Left Wing', difficulty: 1 },
    { name: 'Charles De Ketelaere', nation: 'Belgium', age: 22, position: 'Striker', difficulty: 2 },
    { name: 'Jeremy Doku', nation: 'Belgium', age: 21, position: 'Right Wing', difficulty: 2 },
    { name: 'Romelu Lukaku', nation: 'Belgium', age: 31, position: 'Striker', difficulty: 1 },
    { name: 'Dodi Lukebakio', nation: 'Belgium', age: 26, position: 'Right Wing', difficulty: 2 },
    { name: 'Loïs Openda', nation: 'Belgium', age: 23, position: 'Striker', difficulty: 2 },

    // Adding Croatian players
    { name: 'Ivica Ivusic', nation: 'Croatia', age: 28, position: 'Goalie', difficulty: 2 },
    { name: 'Nediljko Labrovic', nation: 'Croatia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Dominik Livakovic', nation: 'Croatia', age: 29, position: 'Goalie', difficulty: 2 },
    { name: 'Martin Erlic', nation: 'Croatia', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Josko Gvardiol', nation: 'Croatia', age: 22, position: 'Center Back', difficulty: 1 },
    { name: 'Josip Juranovic', nation: 'Croatia', age: 28, position: 'Right Back', difficulty: 2 },
    { name: 'Marin Pongracic', nation: 'Croatia', age: 26, position: 'Center Back', difficulty: 3 },
    { name: 'Borna Sosa', nation: 'Croatia', age: 26, position: 'Left Back', difficulty: 2 },
    { name: 'Josip Stanisic', nation: 'Croatia', age: 23, position: 'Right Back', difficulty: 2 },
    { name: 'Josip sutalo', nation: 'Croatia', age: 23, position: 'Center Back', difficulty: 2 },
    { name: 'Domagoj Vida', nation: 'Croatia', age: 34, position: 'Center Back', difficulty: 2 },
    { name: 'Martin Baturina', nation: 'Croatia', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Marcelo Brozovic', nation: 'Croatia', age: 30, position: 'Midfielder', difficulty: 1 },
    { name: 'Mateo Kovacic', nation: 'Croatia', age: 29, position: 'Midfielder', difficulty: 1 },
    { name: 'Lovro Majer', nation: 'Croatia', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Luka Modric', nation: 'Croatia', age: 38, position: 'Midfielder', difficulty: 1 },
    { name: 'Mario Pasalic', nation: 'Croatia', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Luka Sucic', nation: 'Croatia', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Nikola Vlasic', nation: 'Croatia', age: 25, position: 'Midfielder', difficulty: 2 },
    { name: 'Ante Budimir', nation: 'Croatia', age: 32, position: 'Striker', difficulty: 2 },
    { name: 'Luka Ivanusec', nation: 'Croatia', age: 24, position: 'Left Wing', difficulty: 2 },
    { name: 'Andrej Kramaric', nation: 'Croatia', age: 32, position: 'Striker', difficulty: 2 },
    { name: 'Marco Pasalic', nation: 'Croatia', age: 22, position: 'Right Wing', difficulty: 3 },
    { name: 'Ivan Perisic', nation: 'Croatia', age: 35, position: 'Left Wing', difficulty: 1 },
    { name: 'Bruno Petkovic', nation: 'Croatia', age: 28, position: 'Striker', difficulty: 2 },
    { name: 'Marko Pjaca', nation: 'Croatia', age: 28, position: 'Right Wing', difficulty: 2 },

    // Adding Czechia players
    { name: 'Vitězslav Jaros', nation: 'Czechia', age: 22, position: 'Goalie', difficulty: 3 },
    { name: 'Matěj Kovař', nation: 'Czechia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Jindřich Staněk', nation: 'Czechia', age: 28, position: 'Goalie', difficulty: 3 },
    { name: 'Vladimir Coufal', nation: 'Czechia', age: 30, position: 'Right Back', difficulty: 1 },
    { name: 'David Douděra', nation: 'Czechia', age: 25, position: 'Right Back', difficulty: 3 },
    { name: 'Robin Hranac', nation: 'Czechia', age: 22, position: 'Center Back', difficulty: 3 },
    { name: 'David Jurasek', nation: 'Czechia', age: 23, position: 'Left Back', difficulty: 3 },
    { name: 'Ladislav Krejci', nation: 'Czechia', age: 24, position: 'Center Back', difficulty: 3 },
    { name: 'Martin Vitik', nation: 'Czechia', age: 20, position: 'Center Back', difficulty: 3 },
    { name: 'Tomas Vlcek', nation: 'Czechia', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'David Zima', nation: 'Czechia', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Antonin Barak', nation: 'Czechia', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Lukas cerv', nation: 'Czechia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Tomas Holes', nation: 'Czechia', age: 30, position: 'Midfielder', difficulty: 2 },
    { name: 'Matěj Jurasek', nation: 'Czechia', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Ondřej Lingr', nation: 'Czechia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Lukas Provod', nation: 'Czechia', age: 26, position: 'Midfielder', difficulty: 2 },
    { name: 'Michal Sadilek', nation: 'Czechia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Tomas Soucek', nation: 'Czechia', age: 28, position: 'Defensive Midfield', difficulty: 1 },
    { name: 'Pavel sulc', nation: 'Czechia', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Vaclav cerny', nation: 'Czechia', age: 25, position: 'Right Wing', difficulty: 2 },
    { name: 'Tomas Chory', nation: 'Czechia', age: 28, position: 'Striker', difficulty: 3 },
    { name: 'Mojmir Chytil', nation: 'Czechia', age: 24, position: 'Striker', difficulty: 3 },
    { name: 'Adam Hlozek', nation: 'Czechia', age: 21, position: 'Striker', difficulty: 2 },
    { name: 'Jan Kuchta', nation: 'Czechia', age: 27, position: 'Striker', difficulty: 2 },
    { name: 'Patrik Schick', nation: 'Czechia', age: 28, position: 'Striker', difficulty: 1 },

    // Adding Danish players
    { name: 'Mads Hermansen', nation: 'Denmark', age: 23, position: 'Goalie', difficulty: 3 },
    { name: 'Frederik Rønnow', nation: 'Denmark', age: 31, position: 'Goalie', difficulty: 2 },
    { name: 'Kasper Schmeichel', nation: 'Denmark', age: 37, position: 'Goalie', difficulty: 1 },
    { name: 'Joachim Andersen', nation: 'Denmark', age: 27, position: 'Center Back', difficulty: 2 },
    { name: 'Alexander Bah', nation: 'Denmark', age: 25, position: 'Right Back', difficulty: 3 },
    { name: 'Andreas Christensen', nation: 'Denmark', age: 27, position: 'Center Back', difficulty: 1 },
    { name: 'Mathias Jørgensen', nation: 'Denmark', age: 33, position: 'Center Back', difficulty: 2 },
    { name: 'Simon Kjær', nation: 'Denmark', age: 34, position: 'Center Back', difficulty: 1 },
    { name: 'Rasmus Kristensen', nation: 'Denmark', age: 26, position: 'Right Back', difficulty: 2 },
    { name: 'Victor Kristiansen', nation: 'Denmark', age: 21, position: 'Left Back', difficulty: 3 },
    { name: 'Joakim Mæhle', nation: 'Denmark', age: 26, position: 'Left Back', difficulty: 2 },
    { name: 'Jannik Vestergaard', nation: 'Denmark', age: 31, position: 'Center Back', difficulty: 2 },
    { name: 'Jacob Bruun Larsen', nation: 'Denmark', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Thomas Delaney', nation: 'Denmark', age: 32, position: 'Midfielder', difficulty: 2 },
    { name: 'Anders Dreyer', nation: 'Denmark', age: 25, position: 'Midfielder', difficulty: 3 },
    { name: 'Christian Eriksen', nation: 'Denmark', age: 32, position: 'Midfielder', difficulty: 1 },
    { name: 'Morten Hjulmand', nation: 'Denmark', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Pierre-Emile Højbjerg', nation: 'Denmark', age: 28, position: 'Defensive Midfield', difficulty: 1 },
    { name: 'Mathias Jensen', nation: 'Denmark', age: 27, position: 'Midfielder', difficulty: 2 },
    { name: 'Christian Nørgaard', nation: 'Denmark', age: 29, position: 'Midfielder', difficulty: 2 },
    { name: 'Mikkel Damsgaard', nation: 'Denmark', age: 23, position: 'Striker', difficulty: 2 },
    { name: 'Kasper Dolberg', nation: 'Denmark', age: 25, position: 'Striker', difficulty: 2 },
    { name: 'Rasmus Højlund', nation: 'Denmark', age: 20, position: 'Striker', difficulty: 1 },
    { name: 'Andreas Skov Olsen', nation: 'Denmark', age: 23, position: 'Right Wing', difficulty: 2 },
    { name: 'Yussuf Poulsen', nation: 'Denmark', age: 29, position: 'Striker', difficulty: 2 },
    { name: 'Jonas Wind', nation: 'Denmark', age: 24, position: 'Striker', difficulty: 2 },

    // Adding English players
    { name: 'Dean Henderson', nation: 'England', age: 26, position: 'Goalie', difficulty: 2 },
    { name: 'Jordan Pickford', nation: 'England', age: 30, position: 'Goalie', difficulty: 1 },
    { name: 'Aaron Ramsdale', nation: 'England', age: 25, position: 'Goalie', difficulty: 1 },
    { name: 'Trent Alexander-Arnold', nation: 'England', age: 25, position: 'Right Back', difficulty: 1 },
    { name: 'Lewis Dunk', nation: 'England', age: 32, position: 'Center Back', difficulty: 2 },
    { name: 'Joe Gomez', nation: 'England', age: 26, position: 'Center Back', difficulty: 2 },
    { name: 'Marc Guehi', nation: 'England', age: 23, position: 'Center Back', difficulty: 3 },
    { name: 'Ezri Konsa', nation: 'England', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Luke Shaw', nation: 'England', age: 28, position: 'Left Back', difficulty: 1 },
    { name: 'John Stones', nation: 'England', age: 29, position: 'Center Back', difficulty: 1 },
    { name: 'Kieran Trippier', nation: 'England', age: 33, position: 'Right Back', difficulty: 1 },
    { name: 'Kyle Walker', nation: 'England', age: 34, position: 'Right Back', difficulty: 1 },
    { name: 'Jude Bellingham', nation: 'England', age: 20, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Phil Foden', nation: 'England', age: 24, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Conor Gallagher', nation: 'England', age: 23, position: 'Midfielder', difficulty: 2 },
    { name: 'Kobbie Mainoo', nation: 'England', age: 18, position: 'Midfielder', difficulty: 2 },
    { name: 'Cole Palmer', nation: 'England', age: 21, position: 'Right Wing', difficulty: 1 },
    { name: 'Declan Rice', nation: 'England', age: 25, position: 'Midfielder', difficulty: 1 },
    { name: 'Adam Wharton', nation: 'England', age: 19, position: 'Defensive Midfield', difficulty: 3 },
    { name: 'Jarrod Bowen', nation: 'England', age: 27, position: 'Right Wing', difficulty: 2 },
    { name: 'Eberechi Eze', nation: 'England', age: 25, position: 'Attacking Midfield', difficulty: 2 },
    { name: 'Anthony Gordon', nation: 'England', age: 23, position: 'Left Wing', difficulty: 2 },
    { name: 'Harry Kane', nation: 'England', age: 30, position: 'Striker', difficulty: 1 },
    { name: 'Bukayo Saka', nation: 'England', age: 22, position: 'Right Wing', difficulty: 1 },
    { name: 'Ivan Toney', nation: 'England', age: 27, position: 'Striker', difficulty: 2 },
    { name: 'Ollie Watkins', nation: 'England', age: 27, position: 'Striker', difficulty: 2 },

    // Adding French players
    { name: 'Alphonse Areola', nation: 'France', age: 30, position: 'Goalie', difficulty: 2 },
    { name: 'Mike Maignan', nation: 'France', age: 28, position: 'Goalie', difficulty: 1 },
    { name: 'Brice Samba', nation: 'France', age: 29, position: 'Goalie', difficulty: 2 },
    { name: 'Jonathan Clauss', nation: 'France', age: 31, position: 'Right Back', difficulty: 3 },
    { name: 'Theo Hernandez', nation: 'France', age: 26, position: 'Left Back', difficulty: 1 },
    { name: 'Ibrahima Konate', nation: 'France', age: 24, position: 'Center Back', difficulty: 2 },
    { name: 'Jules Kounde', nation: 'France', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Ferland Mendy', nation: 'France', age: 28, position: 'Left Back', difficulty: 2 },
    { name: 'Benjamin Pavard', nation: 'France', age: 27, position: 'Right Back', difficulty: 1 },
    { name: 'William Saliba', nation: 'France', age: 22, position: 'Center Back', difficulty: 1 },
    { name: 'Dayot Upamecano', nation: 'France', age: 25, position: 'Center Back', difficulty: 2 },
    { name: 'Eduardo Camavinga', nation: 'France', age: 21, position: 'Midfielder', difficulty: 1 },
    { name: 'Youssouf Fofana', nation: 'France', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Antoine Griezmann', nation: 'France', age: 32, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'N\'Golo Kante', nation: 'France', age: 32, position: 'Defensive Midfield', difficulty: 1 },
    { name: 'Adrien Rabiot', nation: 'France', age: 28, position: 'Midfielder', difficulty: 2 },
    { name: 'Aurelien Tchouameni', nation: 'France', age: 23, position: 'Midfielder', difficulty: 1 },
    { name: 'Warren Zaïre-Emery', nation: 'France', age: 17, position: 'Midfielder', difficulty: 3 },
    { name: 'Bradley Barcola', nation: 'France', age: 21, position: 'Right Wing', difficulty: 3 },
    { name: 'Kingsley Coman', nation: 'France', age: 27, position: 'Right Wing', difficulty: 1 },
    { name: 'Ousmane Dembele', nation: 'France', age: 26, position: 'Right Wing', difficulty: 1 },
    { name: 'Olivier Giroud', nation: 'France', age: 37, position: 'Striker', difficulty: 1 },
    { name: 'Randal Kolo Muani', nation: 'France', age: 25, position: 'Striker', difficulty: 2 },
    { name: 'Kylian Mbappe', nation: 'France', age: 25, position: 'Right Wing', difficulty: 1 },
    { name: 'Marcus Thuram', nation: 'France', age: 26, position: 'Striker', difficulty: 2 },

        // Adding Georgian players
    { name: 'Luka Gugeshashvili', nation: 'Georgia', age: 24, position: 'Goalie', difficulty: 3 },
    { name: 'Giorgi Loria', nation: 'Georgia', age: 37, position: 'Goalie', difficulty: 3 },
    { name: 'Giorgi Mamardashvili', nation: 'Georgia', age: 23, position: 'Goalie', difficulty: 3 },
    { name: 'Lasha Dvali', nation: 'Georgia', age: 28, position: 'Center Back', difficulty: 3 },
    { name: 'Giorgi Gocholeishvili', nation: 'Georgia', age: 22, position: 'Right Back', difficulty: 3 },
    { name: 'Giorgi Gvelesiani', nation: 'Georgia', age: 32, position: 'Center Back', difficulty: 3 },
    { name: 'Otar Kakabadze', nation: 'Georgia', age: 28, position: 'Right Back', difficulty: 3 },
    { name: 'Guram Kashia', nation: 'Georgia', age: 35, position: 'Center Back', difficulty: 3 },
    { name: 'Solomon Kverkvelia', nation: 'Georgia', age: 31, position: 'Center Back', difficulty: 3 },
    { name: 'Luka Lochoshvili', nation: 'Georgia', age: 25, position: 'Center Back', difficulty: 3 },
    { name: 'Jemal Tabidze', nation: 'Georgia', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Sandro Altunashvili', nation: 'Georgia', age: 23, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Chakvetadze', nation: 'Georgia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Zuriko Davitashvili', nation: 'Georgia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Otar Kiteishvili', nation: 'Georgia', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Kochorashvili', nation: 'Georgia', age: 24, position: 'Midfielder', difficulty: 3 },
    { name: 'Nika Kvekveskiri', nation: 'Georgia', age: 31, position: 'Midfielder', difficulty: 3 },
    { name: 'Saba Lobjanidze', nation: 'Georgia', age: 28, position: 'Midfielder', difficulty: 3 },
    { name: 'Anzor Mekvabishvili', nation: 'Georgia', age: 21, position: 'Midfielder', difficulty: 3 },
    { name: 'Gabriel Sigua', nation: 'Georgia', age: 18, position: 'Midfielder', difficulty: 3 },
    { name: 'Levan Shengelia', nation: 'Georgia', age: 27, position: 'Midfielder', difficulty: 3 },
    { name: 'Giorgi Tsitaishvili', nation: 'Georgia', age: 22, position: 'Midfielder', difficulty: 3 },
    { name: 'Khvicha Kvaratskhelia', nation: 'Georgia', age: 22, position: 'Left Wing', difficulty: 1 },
    { name: 'Giorgi Kvilitaia', nation: 'Georgia', age: 30, position: 'Striker', difficulty: 3 },
    { name: 'Georges Mikautadze', nation: 'Georgia', age: 23, position: 'Striker', difficulty: 3 },
    { name: 'Budu Zivzivadze', nation: 'Georgia', age: 29, position: 'Striker', difficulty: 3 },


    // Adding German players
    { name: 'Oliver Baumann', nation: 'Germany', age: 33, position: 'Goalie', difficulty: 2 },
    { name: 'Manuel Neuer', nation: 'Germany', age: 38, position: 'Goalie', difficulty: 1 },
    { name: 'Marc-Andre ter Stegen', nation: 'Germany', age: 32, position: 'Goalie', difficulty: 1 },
    { name: 'Waldemar Anton', nation: 'Germany', age: 27, position: 'Center Back', difficulty: 3 },
    { name: 'Benjamin Henrichs', nation: 'Germany', age: 26, position: 'Right Back', difficulty: 2 },
    { name: 'Joshua Kimmich', nation: 'Germany', age: 28, position: 'Right Back', difficulty: 1 },
    { name: 'Robin Koch', nation: 'Germany', age: 26, position: 'Center Back', difficulty: 2 },
    { name: 'Maximilian Mittelstadt', nation: 'Germany', age: 26, position: 'Left Back', difficulty: 3 },
    { name: 'David Raum', nation: 'Germany', age: 25, position: 'Left Back', difficulty: 2 },
    { name: 'Antonio Rudiger', nation: 'Germany', age: 30, position: 'Center Back', difficulty: 1 },
    { name: 'Nico Schlotterbeck', nation: 'Germany', age: 24, position: 'Center Back', difficulty: 2 },
    { name: 'Jonathan Tah', nation: 'Germany', age: 27, position: 'Center Back', difficulty: 2 },
    { name: 'Robert Andrich', nation: 'Germany', age: 29, position: 'Defensive Midfielder', difficulty: 3 },
    { name: 'Chris Fuhrich', nation: 'Germany', age: 25, position: 'Midfielder', difficulty: 3 },
    { name: 'İlkay Gundogan', nation: 'Germany', age: 33, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Pascal Gross', nation: 'Germany', age: 33, position: 'Midfielder', difficulty: 2 },
    { name: 'Toni Kroos', nation: 'Germany', age: 34, position: 'Midfielder', difficulty: 1 },
    { name: 'Jamal Musiala', nation: 'Germany', age: 21, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Aleksandar Pavlovic', nation: 'Germany', age: 20, position: 'Midfielder', difficulty: 3 },
    { name: 'Leroy Sane', nation: 'Germany', age: 28, position: 'Right Wing', difficulty: 1 },
    { name: 'Florian Wirtz', nation: 'Germany', age: 21, position: 'Attacking Midfield', difficulty: 1 },
    { name: 'Maximilian Beier', nation: 'Germany', age: 21, position: 'Striker', difficulty: 3 },
    { name: 'Niclas Fullkrug', nation: 'Germany', age: 30, position: 'Striker', difficulty: 2 },
    { name: 'Kai Havertz', nation: 'Germany', age: 24, position: 'Striker', difficulty: 1 },
    { name: 'Thomas Muller', nation: 'Germany', age: 34, position: 'Striker', difficulty: 1 },
    { name: 'Deniz Undav', nation: 'Germany', age: 27, position: 'Striker', difficulty: 3 },

// Adding Italian players
{ name: 'Gianluigi Donnarumma', nation: 'Italy', age: 25, position: 'Goalie', difficulty: 1 },
{ name: 'Alex Meret', nation: 'Italy', age: 26, position: 'Goalie', difficulty: 2 },
{ name: 'Guglielmo Vicario', nation: 'Italy', age: 27, position: 'Goalie', difficulty: 2 },
{ name: 'Alessandro Bastoni', nation: 'Italy', age: 24, position: 'Center Back', difficulty: 1 },
{ name: 'Raoul Bellanova', nation: 'Italy', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Alessandro Buongiorno', nation: 'Italy', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Riccardo Calafiori', nation: 'Italy', age: 21, position: 'Left Back', difficulty: 3 },
{ name: 'Andrea Cambiaso', nation: 'Italy', age: 23, position: 'Left Back', difficulty: 3 },
{ name: 'Matteo Darmian', nation: 'Italy', age: 34, position: 'Right Back', difficulty: 2 },
{ name: 'Giovanni Di Lorenzo', nation: 'Italy', age: 30, position: 'Right Back', difficulty: 1 },
{ name: 'Federico Dimarco', nation: 'Italy', age: 25, position: 'Left Back', difficulty: 2 },
{ name: 'Federico Gatti', nation: 'Italy', age: 25, position: 'Center Back', difficulty: 3 },
{ name: 'Gianluca Mancini', nation: 'Italy', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Nicolo Barella', nation: 'Italy', age: 26, position: 'Midfielder', difficulty: 1 },
{ name: 'Bryan Cristante', nation: 'Italy', age: 28, position: 'Midfielder', difficulty: 2 },
{ name: 'Nicolo Fagioli', nation: 'Italy', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Davide Frattesi', nation: 'Italy', age: 24, position: 'Midfielder', difficulty: 2 },
{ name: 'Jorginho', nation: 'Italy', age: 32, position: 'Defensive Midfielder', difficulty: 1 },
{ name: 'Lorenzo Pellegrini', nation: 'Italy', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Federico Chiesa', nation: 'Italy', age: 26, position: 'Right Wing', difficulty: 1 },
{ name: 'Stephan El Shaarawy', nation: 'Italy', age: 31, position: 'Left Wing', difficulty: 2 },
{ name: 'Michael Folorunsho', nation: 'Italy', age: 25, position: 'Striker', difficulty: 3 },
{ name: 'Giacomo Raspadori', nation: 'Italy', age: 23, position: 'Striker', difficulty: 2 },
{ name: 'Mateo Retegui', nation: 'Italy', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Gianluca Scamacca', nation: 'Italy', age: 24, position: 'Striker', difficulty: 2 },
{ name: 'Mattia Zaccagni', nation: 'Italy', age: 28, position: 'Left Wing', difficulty: 3 },

// Adding Netherlands players
{ name: 'Justin Bijlow', nation: 'Netherlands', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Mark Flekken', nation: 'Netherlands', age: 30, position: 'Goalie', difficulty: 3 },
{ name: 'Bart Verbruggen', nation: 'Netherlands', age: 21, position: 'Goalie', difficulty: 3 },
{ name: 'Nathan Ake', nation: 'Netherlands', age: 29, position: 'Center Back', difficulty: 1 },
{ name: 'Daley Blind', nation: 'Netherlands', age: 34, position: 'Left Back', difficulty: 1 },
{ name: 'Matthijs de Ligt', nation: 'Netherlands', age: 24, position: 'Center Back', difficulty: 1 },
{ name: 'Stefan de Vrij', nation: 'Netherlands', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Denzel Dumfries', nation: 'Netherlands', age: 28, position: 'Right Back', difficulty: 1 },
{ name: 'Lutsharel Geertruida', nation: 'Netherlands', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Micky van de Ven', nation: 'Netherlands', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Virgil van Dijk', nation: 'Netherlands', age: 32, position: 'Center Back', difficulty: 1 },
{ name: 'Frenkie de Jong', nation: 'Netherlands', age: 26, position: 'Midfielder', difficulty: 1 },
{ name: 'Ryan Gravenberch', nation: 'Netherlands', age: 21, position: 'Midfielder', difficulty: 2 },
{ name: 'Teun Koopmeiners', nation: 'Netherlands', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'Tijjani Reijnders', nation: 'Netherlands', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Jerdy Schouten', nation: 'Netherlands', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Joey Veerman', nation: 'Netherlands', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Georginio Wijnaldum', nation: 'Netherlands', age: 33, position: 'Midfielder', difficulty: 1 },
{ name: 'Steven Bergwijn', nation: 'Netherlands', age: 26, position: 'Left Wing', difficulty: 2 },
{ name: 'Brian Brobbey', nation: 'Netherlands', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Memphis Depay', nation: 'Netherlands', age: 29, position: 'Left Wing', difficulty: 1 },
{ name: 'Jeremie Frimpong', nation: 'Netherlands', age: 22, position: 'Right Wing', difficulty: 2 },
{ name: 'Cody Gakpo', nation: 'Netherlands', age: 24, position: 'Striker', difficulty: 1 },
{ name: 'Donyell Malen', nation: 'Netherlands', age: 24, position: 'Right Wing', difficulty: 2 },
{ name: 'Xavi Simons', nation: 'Netherlands', age: 20, position: 'Attacking Midfield', difficulty: 3 },
{ name: 'Wout Weghorst', nation: 'Netherlands', age: 31, position: 'Striker', difficulty: 2 },

// Adding Polish players
{ name: 'Marcin Bulka', nation: 'Poland', age: 24, position: 'Goalie', difficulty: 3 },
{ name: 'lukasz Skorupski', nation: 'Poland', age: 32, position: 'Goalie', difficulty: 2 },
{ name: 'Wojciech Szczesny', nation: 'Poland', age: 34, position: 'Goalie', difficulty: 1 },
{ name: 'Jan Bednarek', nation: 'Poland', age: 28, position: 'Center Back', difficulty: 2 },
{ name: 'Bartosz Bereszynski', nation: 'Poland', age: 31, position: 'Right Back', difficulty: 2 },
{ name: 'Przemyslaw Frankowski', nation: 'Poland', age: 28, position: 'Right Back', difficulty: 2 },
{ name: 'Jakub Kiwior', nation: 'Poland', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Tymoteusz Puchacz', nation: 'Poland', age: 24, position: 'Left Back', difficulty: 3 },
{ name: 'Bartosz Salamon', nation: 'Poland', age: 32, position: 'Center Back', difficulty: 3 },
{ name: 'Sebastian Walukiewicz', nation: 'Poland', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Pawel Dawidowicz', nation: 'Poland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Kamil Grosicki', nation: 'Poland', age: 35, position: 'Left Wing', difficulty: 2 },
{ name: 'Jakub Moder', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Jakub Piotrowski', nation: 'Poland', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Taras Romanczuk', nation: 'Poland', age: 31, position: 'Midfielder', difficulty: 3 },
{ name: 'Bartosz Slisz', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Damian Szymanski', nation: 'Poland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Sebastian Szymanski', nation: 'Poland', age: 24, position: 'Midfielder', difficulty: 2 },
{ name: 'Kacper Urbanski', nation: 'Poland', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'Nicola Zalewski', nation: 'Poland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Piotr Zielinski', nation: 'Poland', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Adam Buksa', nation: 'Poland', age: 27, position: 'Striker', difficulty: 3 },
{ name: 'Robert Lewandowski', nation: 'Poland', age: 35, position: 'Striker', difficulty: 1 },
{ name: 'Krzysztof Piatek', nation: 'Poland', age: 28, position: 'Striker', difficulty: 2 },
{ name: 'Michal Skoras', nation: 'Poland', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Karol Swiderski', nation: 'Poland', age: 27, position: 'Striker', difficulty: 3 },

// Adding Portuguese players
{ name: 'Diogo Costa', nation: 'Portugal', age: 24, position: 'Goalie', difficulty: 2 },
{ name: 'Rui Patricio', nation: 'Portugal', age: 35, position: 'Goalie', difficulty: 2 },
{ name: 'Jose Sa', nation: 'Portugal', age: 31, position: 'Goalie', difficulty: 3 },
{ name: 'Joao Cancelo', nation: 'Portugal', age: 29, position: 'Right Back', difficulty: 1 },
{ name: 'Diogo Dalot', nation: 'Portugal', age: 25, position: 'Right Back', difficulty: 2 },
{ name: 'Ruben Dias', nation: 'Portugal', age: 26, position: 'Center Back', difficulty: 1 },
{ name: 'Goncalo Inacio', nation: 'Portugal', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Nuno Mendes', nation: 'Portugal', age: 21, position: 'Left Back', difficulty: 2 },
{ name: 'Pepe', nation: 'Portugal', age: 40, position: 'Center Back', difficulty: 1 },
{ name: 'Nelson Semedo', nation: 'Portugal', age: 30, position: 'Right Back', difficulty: 2 },
{ name: 'Antonio Silva', nation: 'Portugal', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Danilo', nation: 'Portugal', age: 32, position: 'Defensive Midfielder', difficulty: 2 },
{ name: 'Bruno Fernandes', nation: 'Portugal', age: 29, position: 'Attacking Midfield', difficulty: 1 },
{ name: 'Pedro Neto', nation: 'Portugal', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Joao Neves', nation: 'Portugal', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'Ruben Neves', nation: 'Portugal', age: 26, position: 'Defensive Midfield', difficulty: 2 },
{ name: 'Matheus Nunes', nation: 'Portugal', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'Joao Palhinha', nation: 'Portugal', age: 28, position: 'Defensive Midfield', difficulty: 2 },
{ name: 'Bernardo Silva', nation: 'Portugal', age: 29, position: 'Attacking Midfield', difficulty: 1 },
{ name: 'Vitinha', nation: 'Portugal', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'Francisco Conceicao', nation: 'Portugal', age: 21, position: 'Right Wing', difficulty: 3 },
{ name: 'Joao Felix', nation: 'Portugal', age: 24, position: 'Striker', difficulty: 1 },
{ name: 'Diogo Jota', nation: 'Portugal', age: 27, position: 'Left Wing', difficulty: 1 },
{ name: 'Rafael Leao', nation: 'Portugal', age: 24, position: 'Left Wing', difficulty: 2 },
{ name: 'Goncalo Ramos', nation: 'Portugal', age: 22, position: 'Striker', difficulty: 2 },
{ name: 'Cristiano Ronaldo', nation: 'Portugal', age: 39, position: 'Striker', difficulty: 1 },

// Adding Romanian players
{ name: 'Horatiu Moldovan', nation: 'Romania', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Florin Nita', nation: 'Romania', age: 36, position: 'Goalie', difficulty: 3 },
{ name: 'Ștefan Tarnovanu', nation: 'Romania', age: 23, position: 'Goalie', difficulty: 3 },
{ name: 'Nicușor Bancu', nation: 'Romania', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'Andrei Burca', nation: 'Romania', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'Radu Dragusin', nation: 'Romania', age: 21, position: 'Center Back', difficulty: 3 },
{ name: 'Vasile Mogos', nation: 'Romania', age: 30, position: 'Right Back', difficulty: 3 },
{ name: 'Ionut Nedelcearu', nation: 'Romania', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Bogdan Racovitan', nation: 'Romania', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Andrei Ratiu', nation: 'Romania', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Adrian Rus', nation: 'Romania', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Alexandru Cicaldau', nation: 'Romania', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Ianis Hagi', nation: 'Romania', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Marius Marin', nation: 'Romania', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Razvan Marin', nation: 'Romania', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Darius Olaru', nation: 'Romania', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Deian Sorescu', nation: 'Romania', age: 26, position: 'Right Wing', difficulty: 3 },
{ name: 'Nicolae Stanciu', nation: 'Romania', age: 30, position: 'Midfielder', difficulty: 3 },
{ name: 'Adrian sut', nation: 'Romania', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Denis Alibec', nation: 'Romania', age: 32, position: 'Striker', difficulty: 3 },
{ name: 'Daniel Birligea', nation: 'Romania', age: 23, position: 'Striker', difficulty: 3 },
{ name: 'Florinel Coman', nation: 'Romania', age: 25, position: 'Left Wing', difficulty: 3 },
{ name: 'Denis Dragus', nation: 'Romania', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Dennis Man', nation: 'Romania', age: 25, position: 'Right Wing', difficulty: 3 },
{ name: 'Valentin Mihaila', nation: 'Romania', age: 24, position: 'Left Wing', difficulty: 3 },
{ name: 'George Puscas', nation: 'Romania', age: 28, position: 'Striker', difficulty: 3 },


// Adding Scottish players
{ name: 'Zander Clark', nation: 'Scotland', age: 31, position: 'Goalie', difficulty: 3 },
{ name: 'Angus Gunn', nation: 'Scotland', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Liam Kelly', nation: 'Scotland', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Liam Cooper', nation: 'Scotland', age: 32, position: 'Center Back', difficulty: 3 },
{ name: 'Grant Hanley', nation: 'Scotland', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Jack Hendry', nation: 'Scotland', age: 28, position: 'Center Back', difficulty: 3 },
{ name: 'Ross McCrorie', nation: 'Scotland', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Scott McKenna', nation: 'Scotland', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Ryan Porteous', nation: 'Scotland', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Anthony Ralston', nation: 'Scotland', age: 25, position: 'Right Back', difficulty: 3 },
{ name: 'Andrew Robertson', nation: 'Scotland', age: 30, position: 'Left Back', difficulty: 1 },
{ name: 'Greg Taylor', nation: 'Scotland', age: 25, position: 'Left Back', difficulty: 3 },
{ name: 'Kieran Tierney', nation: 'Scotland', age: 27, position: 'Left Back', difficulty: 1 },
{ name: 'Stuart Armstrong', nation: 'Scotland', age: 31, position: 'Midfielder', difficulty: 2 },
{ name: 'James Forrest', nation: 'Scotland', age: 32, position: 'Right Wing', difficulty: 2 },
{ name: 'Billy Gilmour', nation: 'Scotland', age: 22, position: 'Midfielder', difficulty: 2 },
{ name: 'Ryan Jack', nation: 'Scotland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'John McGinn', nation: 'Scotland', age: 29, position: 'Midfielder', difficulty: 1 },
{ name: 'Callum McGregor', nation: 'Scotland', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Kenny McLean', nation: 'Scotland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Scott McTominay', nation: 'Scotland', age: 27, position: 'Midfielder', difficulty: 1 },
{ name: 'Lewis Morgan', nation: 'Scotland', age: 27, position: 'Right Wing', difficulty: 3 },
{ name: 'Che Adams', nation: 'Scotland', age: 27, position: 'Striker', difficulty: 2 },
{ name: 'Ryan Christie', nation: 'Scotland', age: 28, position: 'Right Wing', difficulty: 2 },
{ name: 'Tommy Conway', nation: 'Scotland', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Lawrence Shankland', nation: 'Scotland', age: 28, position: 'Striker', difficulty: 3 },

// Adding Serbian players
{ name: 'Vanja Milinkovic-Savic', nation: 'Serbia', age: 26, position: 'Goalie', difficulty: 3 },
{ name: 'dorde Petrovic', nation: 'Serbia', age: 23, position: 'Goalie', difficulty: 3 },
{ name: 'Predrag Rajkovic', nation: 'Serbia', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Srdan Babic', nation: 'Serbia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Nikola Milenkovic', nation: 'Serbia', age: 26, position: 'Center Back', difficulty: 2 },
{ name: 'Filip Mladenovic', nation: 'Serbia', age: 32, position: 'Left Back', difficulty: 3 },
{ name: 'Strahinja Pavlovic', nation: 'Serbia', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Uros Spajic', nation: 'Serbia', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'Nemanja Stojic', nation: 'Serbia', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Milos Veljkovic', nation: 'Serbia', age: 28, position: 'Center Back', difficulty: 3 },
{ name: 'Veljko Birmancevic', nation: 'Serbia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Mijat Gacinovic', nation: 'Serbia', age: 29, position: 'Midfielder', difficulty: 3 },
{ name: 'Nemanja Gudelj', nation: 'Serbia', age: 32, position: 'Midfielder', difficulty: 2 },
{ name: 'Ivan Ilic', nation: 'Serbia', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Sasa Lukic', nation: 'Serbia', age: 27, position: 'Midfielder', difficulty: 3 },
{ name: 'Nemanja Maksimovic', nation: 'Serbia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Srdjan Mijailovic', nation: 'Serbia', age: 30, position: 'Midfielder', difficulty: 3 },
{ name: 'Sergej Milinkovic-Savic', nation: 'Serbia', age: 28, position: 'Midfielder', difficulty: 2 },
{ name: 'Lazar Vujadin Samardzic', nation: 'Serbia', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Luka Jovic', nation: 'Serbia', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Filip Kostic', nation: 'Serbia', age: 30, position: 'Left Wing', difficulty: 2 },
{ name: 'Aleksandar Mitrovic', nation: 'Serbia', age: 29, position: 'Striker', difficulty: 1 },
{ name: 'Petar Ratkov', nation: 'Serbia', age: 20, position: 'Striker', difficulty: 3 },
{ name: 'Dusan Tadic', nation: 'Serbia', age: 35, position: 'Right Wing', difficulty: 1 },
{ name: 'Dusan Vlahovic', nation: 'Serbia', age: 24, position: 'Striker', difficulty: 1 },
{ name: 'Andrija Zivkovic', nation: 'Serbia', age: 27, position: 'Right Wing', difficulty: 3 },

// Adding Slovakian players
{ name: 'Martin Dubravka', nation: 'Slovakia', age: 35, position: 'Goalie', difficulty: 2 },
{ name: 'Henrich Ravas', nation: 'Slovakia', age: 25, position: 'Goalie', difficulty: 3 },
{ name: 'Marek Rodak', nation: 'Slovakia', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Vernon De Marco', nation: 'Slovakia', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'Norbert Gyomber', nation: 'Slovakia', age: 31, position: 'Center Back', difficulty: 3 },
{ name: 'David Hancko', nation: 'Slovakia', age: 25, position: 'Left Back', difficulty: 3 },
{ name: 'Sebastian Kosa', nation: 'Slovakia', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Adam Obert', nation: 'Slovakia', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Peter Pekarik', nation: 'Slovakia', age: 36, position: 'Right Back', difficulty: 2 },
{ name: 'Milan skriniar', nation: 'Slovakia', age: 28, position: 'Center Back', difficulty: 1 },
{ name: 'Denis Vavro', nation: 'Slovakia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Laszlo Benes', nation: 'Slovakia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Matus Bero', nation: 'Slovakia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Ondrej Duda', nation: 'Slovakia', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Patrik Hrosovsky', nation: 'Slovakia', age: 31, position: 'Midfielder', difficulty: 3 },
{ name: 'Juraj Kucka', nation: 'Slovakia', age: 36, position: 'Midfielder', difficulty: 3 },
{ name: 'Stanislav Lobotka', nation: 'Slovakia', age: 29, position: 'Midfielder', difficulty: 2 },
{ name: 'Tomas Rigo', nation: 'Slovakia', age: 20, position: 'Midfielder', difficulty: 3 },
{ name: 'Robert Bozenik', nation: 'Slovakia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'David Duris', nation: 'Slovakia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Lukas Haraslin', nation: 'Slovakia', age: 27, position: 'Left Wing', difficulty: 3 },
{ name: 'Leo Sauer', nation: 'Slovakia', age: 18, position: 'Left Wing', difficulty: 3 },
{ name: 'Ivan Schranz', nation: 'Slovakia', age: 30, position: 'Right Wing', difficulty: 3 },
{ name: 'David Strelec', nation: 'Slovakia', age: 22, position: 'Striker', difficulty: 3 },
{ name: 'Tomas Suslov', nation: 'Slovakia', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Ľubomir Tupta', nation: 'Slovakia', age: 25, position: 'Striker', difficulty: 3 },

// Adding Slovenian players
{ name: 'Vid Belec', nation: 'Slovenia', age: 33, position: 'Goalie', difficulty: 3 },
{ name: 'Jan Oblak', nation: 'Slovenia', age: 31, position: 'Goalie', difficulty: 1 },
{ name: 'Igor Vekic', nation: 'Slovenia', age: 27, position: 'Goalie', difficulty: 3 },
{ name: 'Jure Balkovec', nation: 'Slovenia', age: 29, position: 'Left Back', difficulty: 3 },
{ name: 'Jaka Bijol', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Miha Blazic', nation: 'Slovenia', age: 30, position: 'Center Back', difficulty: 3 },
{ name: 'David Brekalo', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Vanja Drkusic', nation: 'Slovenia', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Erik Janza', nation: 'Slovenia', age: 30, position: 'Left Back', difficulty: 3 },
{ name: 'zan Karnicnik', nation: 'Slovenia', age: 27, position: 'Right Back', difficulty: 3 },
{ name: 'Jon Gorenc Stankovic', nation: 'Slovenia', age: 27, position: 'Center Back', difficulty: 3 },
{ name: 'Petar Stojanovic', nation: 'Slovenia', age: 28, position: 'Right Back', difficulty: 3 },
{ name: 'Timi Elsnik', nation: 'Slovenia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Adam Gnezda cerin', nation: 'Slovenia', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Tomi Horvat', nation: 'Slovenia', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'Josip Ilicic', nation: 'Slovenia', age: 35, position: 'Right Wing', difficulty: 2 },
{ name: 'Jasmin Kurtic', nation: 'Slovenia', age: 34, position: 'Midfielder', difficulty: 3 },
{ name: 'Sandi Lovric', nation: 'Slovenia', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Benjamin Verbic', nation: 'Slovenia', age: 29, position: 'Left Wing', difficulty: 3 },
{ name: 'Adrian Zeljkovic', nation: 'Slovenia', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Nino zugelj', nation: 'Slovenia', age: 23, position: 'Midfielder', difficulty: 3 },
{ name: 'zan Celar', nation: 'Slovenia', age: 24, position: 'Striker', difficulty: 3 },
{ name: 'Jan Mlakar', nation: 'Slovenia', age: 25, position: 'Striker', difficulty: 3 },
{ name: 'Benjamin sesko', nation: 'Slovenia', age: 20, position: 'Striker', difficulty: 2 },
{ name: 'Andraz sporar', nation: 'Slovenia', age: 30, position: 'Striker', difficulty: 3 },
{ name: 'zan Vipotnik', nation: 'Slovenia', age: 21, position: 'Striker', difficulty: 3 },

// Adding Spanish players
{ name: 'David Raya', nation: 'Spain', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Alejandro Remiro', nation: 'Spain', age: 28, position: 'Goalie', difficulty: 3 },
{ name: 'Unai Simon', nation: 'Spain', age: 26, position: 'Goalie', difficulty: 1 },
{ name: 'Dani Carvajal', nation: 'Spain', age: 32, position: 'Right Back', difficulty: 1 },
{ name: 'Marc Cucurella', nation: 'Spain', age: 25, position: 'Left Back', difficulty: 2 },
{ name: 'Alejandro Grimaldo', nation: 'Spain', age: 28, position: 'Left Back', difficulty: 2 },
{ name: 'Aymeric Laporte', nation: 'Spain', age: 29, position: 'Center Back', difficulty: 1 },
{ name: 'Robin Le Normand', nation: 'Spain', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Nacho', nation: 'Spain', age: 34, position: 'Center Back', difficulty: 2 },
{ name: 'Daniel Vivian', nation: 'Spain', age: 24, position: 'Center Back', difficulty: 3 },
{ name: 'Alex Baena', nation: 'Spain', age: 22, position: 'Midfielder', difficulty: 3 },
{ name: 'Mikel Merino', nation: 'Spain', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Mikel Oyarzabal', nation: 'Spain', age: 26, position: 'Attacking Midfield', difficulty: 2 },
{ name: 'Pedri', nation: 'Spain', age: 21, position: 'Midfielder', difficulty: 1 },
{ name: 'Rodri', nation: 'Spain', age: 27, position: 'Defensive Midfield', difficulty: 1 },
{ name: 'Fabian Ruiz', nation: 'Spain', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Nico Williams', nation: 'Spain', age: 21, position: 'Right Wing', difficulty: 2 },
{ name: 'Martin Zubimendi', nation: 'Spain', age: 25, position: 'Midfielder', difficulty: 2 },
{ name: 'Joselu', nation: 'Spain', age: 33, position: 'Striker', difficulty: 2 },
{ name: 'Fermin Lopez', nation: 'Spain', age: 20, position: 'Midfielder', difficulty: 3 },
{ name: 'alvaro Morata', nation: 'Spain', age: 31, position: 'Striker', difficulty: 1 },
{ name: 'Jesus Navas', nation: 'Spain', age: 38, position: 'Right Wing', difficulty: 1 },
{ name: 'Dani Olmo', nation: 'Spain', age: 26, position: 'Left Wing', difficulty: 2 },
{ name: 'Ayoze Perez', nation: 'Spain', age: 30, position: 'Right Wing', difficulty: 3 },
{ name: 'Ferran Torres', nation: 'Spain', age: 23, position: 'Right Wing', difficulty: 2 },
{ name: 'Lamine Yamal', nation: 'Spain', age: 16, position: 'Right Wing', difficulty: 3 },

// Adding Swiss players
{ name: 'Gregor Kobel', nation: 'Switzerland', age: 26, position: 'Goalie', difficulty: 2 },
{ name: 'Yvon Mvogo', nation: 'Switzerland', age: 29, position: 'Goalie', difficulty: 3 },
{ name: 'Yann Sommer', nation: 'Switzerland', age: 35, position: 'Goalie', difficulty: 1 },
{ name: 'Manuel Akanji', nation: 'Switzerland', age: 28, position: 'Center Back', difficulty: 1 },
{ name: 'Nico Elvedi', nation: 'Switzerland', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Ricardo Rodriguez', nation: 'Switzerland', age: 31, position: 'Left Back', difficulty: 2 },
{ name: 'Fabian Schar', nation: 'Switzerland', age: 32, position: 'Center Back', difficulty: 2 },
{ name: 'Leonidas Stergiou', nation: 'Switzerland', age: 21, position: 'Center Back', difficulty: 3 },
{ name: 'Silvan Widmer', nation: 'Switzerland', age: 31, position: 'Right Back', difficulty: 3 },
{ name: 'Cedric Zesiger', nation: 'Switzerland', age: 25, position: 'Center Back', difficulty: 3 },
{ name: 'Michel Aebischer', nation: 'Switzerland', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Remo Freuler', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 2 },
{ name: 'Ardon Jashari', nation: 'Switzerland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Fabian Rieder', nation: 'Switzerland', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Xherdan Shaqiri', nation: 'Switzerland', age: 32, position: 'Right Wing', difficulty: 1 },
{ name: 'Vincent Sierro', nation: 'Switzerland', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Renato Steffen', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Ruben Vargas', nation: 'Switzerland', age: 25, position: 'Right Wing', difficulty: 3 },
{ name: 'Granit Xhaka', nation: 'Switzerland', age: 31, position: 'Defensive Midfield', difficulty: 1 },
{ name: 'Denis Zakaria', nation: 'Switzerland', age: 27, position: 'Midfielder', difficulty: 2 },
{ name: 'Steven Zuber', nation: 'Switzerland', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Zeki Amdouni', nation: 'Switzerland', age: 23, position: 'Striker', difficulty: 3 },
{ name: 'Kwadwo Duah', nation: 'Switzerland', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Breel Embolo', nation: 'Switzerland', age: 27, position: 'Striker', difficulty: 2 },
{ name: 'Dan Ndoye', nation: 'Switzerland', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Noah Okafor', nation: 'Switzerland', age: 23, position: 'Left Wing', difficulty: 2 },

// Adding Turkish players
{ name: 'Altay Bayindir', nation: 'Turkiye', age: 25, position: 'Goalie', difficulty: 2 },
{ name: 'Mert Gunok', nation: 'Turkiye', age: 34, position: 'Goalie', difficulty: 3 },
{ name: 'Ugurcan Cakir', nation: 'Turkiye', age: 28, position: 'Goalie', difficulty: 2 },
{ name: 'Samet Akaydin', nation: 'Turkiye', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Abdulkerim Bardakci', nation: 'Turkiye', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Zeki celik', nation: 'Turkiye', age: 26, position: 'Right Back', difficulty: 2 },
{ name: 'Merih Demiral', nation: 'Turkiye', age: 25, position: 'Center Back', difficulty: 2 },
{ name: 'Ferdi Kadioglu', nation: 'Turkiye', age: 23, position: 'Left Back', difficulty: 3 },
{ name: 'Ahmetcan Kaplan', nation: 'Turkiye', age: 20, position: 'Center Back', difficulty: 3 },
{ name: 'Mert Muldur', nation: 'Turkiye', age: 24, position: 'Right Back', difficulty: 3 },
{ name: 'Hakan calhanoglu', nation: 'Turkiye', age: 30, position: 'Midfielder', difficulty: 1 },
{ name: 'İsmail Yuksek', nation: 'Turkiye', age: 24, position: 'Midfielder', difficulty: 3 },
{ name: 'Kaan Ayhan', nation: 'Turkiye', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Okay Yokuslu', nation: 'Turkiye', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Orkun Kokcu', nation: 'Turkiye', age: 22, position: 'Midfielder', difficulty: 2 },
{ name: 'Salih Ozcan', nation: 'Turkiye', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Yunus Akgun', nation: 'Turkiye', age: 23, position: 'Right Wing', difficulty: 3 },
{ name: 'Kerem Akturkoglu', nation: 'Turkiye', age: 24, position: 'Left Wing', difficulty: 3 },
{ name: 'Arda Guler', nation: 'Turkiye', age: 19, position: 'Midfielder', difficulty: 3 },
{ name: 'İrfan Can Kahveci', nation: 'Turkiye', age: 28, position: 'Midfielder', difficulty: 3 },
{ name: 'Semih Kilicsoy', nation: 'Turkiye', age: 18, position: 'Striker', difficulty: 3 },
{ name: 'Cenk Tosun', nation: 'Turkiye', age: 32, position: 'Striker', difficulty: 2 },
{ name: 'Yusuf Yazici', nation: 'Turkiye', age: 26, position: 'Midfielder', difficulty: 3 },
{ name: 'Bertug Yildirim', nation: 'Turkiye', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Kenan Yildiz', nation: 'Turkiye', age: 18, position: 'Midfielder', difficulty: 3 },
{ name: 'Baris Alper Yilmaz', nation: 'Turkiye', age: 23, position: 'Right Wing', difficulty: 3 },

// Adding Ukrainian players
{ name: 'Georgiy Bushchan', nation: 'Ukraine', age: 29, position: 'Goalie', difficulty: 3 },
{ name: 'Andriy Lunin', nation: 'Ukraine', age: 24, position: 'Goalie', difficulty: 2 },
{ name: 'Anatoliy Trubin', nation: 'Ukraine', age: 22, position: 'Goalie', difficulty: 3 },
{ name: 'Valeriy Bondar', nation: 'Ukraine', age: 23, position: 'Center Back', difficulty: 3 },
{ name: 'Yukhym Konoplia', nation: 'Ukraine', age: 23, position: 'Right Back', difficulty: 3 },
{ name: 'Mykola Matviyenko', nation: 'Ukraine', age: 27, position: 'Center Back', difficulty: 2 },
{ name: 'Bogdan Mykhaylichenko', nation: 'Ukraine', age: 26, position: 'Left Back', difficulty: 3 },
{ name: 'Vitaliy Mykolenko', nation: 'Ukraine', age: 24, position: 'Left Back', difficulty: 2 },
{ name: 'Oleksandr Svatok', nation: 'Ukraine', age: 29, position: 'Center Back', difficulty: 3 },
{ name: 'Maksym Talovierov', nation: 'Ukraine', age: 22, position: 'Center Back', difficulty: 3 },
{ name: 'Oleksandr Tymchyk', nation: 'Ukraine', age: 26, position: 'Right Back', difficulty: 3 },
{ name: 'Illia Zabarnyi', nation: 'Ukraine', age: 21, position: 'Center Back', difficulty: 2 },
{ name: 'Oleksandr Zinchenko', nation: 'Ukraine', age: 27, position: 'Left Back', difficulty: 1 },
{ name: 'Volodymyr Brazhko', nation: 'Ukraine', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Ruslan Malinovskyi', nation: 'Ukraine', age: 30, position: 'Midfielder', difficulty: 2 },
{ name: 'Mykola Shaparenko', nation: 'Ukraine', age: 25, position: 'Midfielder', difficulty: 3 },
{ name: 'Taras Stepanenko', nation: 'Ukraine', age: 34, position: 'Midfielder', difficulty: 3 },
{ name: 'Georgiy Sudakov', nation: 'Ukraine', age: 21, position: 'Midfielder', difficulty: 3 },
{ name: 'Serhiy Sydorchuk', nation: 'Ukraine', age: 32, position: 'Midfielder', difficulty: 3 },
{ name: 'Viktor Tsygankov', nation: 'Ukraine', age: 26, position: 'Right Wing', difficulty: 2 },
{ name: 'Andriy Yarmolenko', nation: 'Ukraine', age: 34, position: 'Right Wing', difficulty: 2 },
{ name: 'Oleksandr Zubkov', nation: 'Ukraine', age: 26, position: 'Right Wing', difficulty: 3 },
{ name: 'Artem Dovbyk', nation: 'Ukraine', age: 26, position: 'Striker', difficulty: 3 },
{ name: 'Mykhailo Mudryk', nation: 'Ukraine', age: 23, position: 'Left Wing', difficulty: 2 },
{ name: 'Vladyslav Vanat', nation: 'Ukraine', age: 21, position: 'Striker', difficulty: 3 },
{ name: 'Roman Yaremchuk', nation: 'Ukraine', age: 28, position: 'Striker', difficulty: 2 },

  ];
  
  const groups = {
    A: ['Germany', 'Hungary', 'Scotland', 'Switzerland'],
    B: ['Spain', 'Croatia', 'Italy', 'Albania'],
    C: ['England', 'Denmark', 'Slovenia', 'Serbia'],
    D: ['France', 'Netherlands', 'Austria', 'Poland'],
    E: ['Belgium', 'Romania', 'Slovakia', 'Ukraine'],
    F: ['Portugal', 'Turkiye', 'Czechia', 'Georgia']
  };
  
  const positionGroups = {
    Forward: ['Left Wing', 'Striker', 'Right Wing'],
    Midfield: ['Defensive Midfield', 'Attacking Midfield', 'Midfielder'],
    Defense: ['Left Back', 'Center Back', 'Right Back'],
    Goalie: ['Goalie']
  };
  
  export { players, groups, positionGroups };
  